# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/XDashDebugger.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/XDashDebugger.proto\x12 org.kobe.xbot.Utilities.Entities\"\x82\x01\n\x07Message\x12\t\n\x01t\x18\x01 \x01(\x01\x12:\n\x02ty\x18\x02 \x01(\x0e\x32..org.kobe.xbot.Utilities.Entities.Message.Type\x12\t\n\x01v\x18\x03 \x01(\x0c\x12\t\n\x01k\x18\x04 \x01(\t\"\x1a\n\x04Type\x12\t\n\x05IMAGE\x10\x00\x12\x07\n\x03LOG\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.XDashDebugger_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=65
  _globals['_MESSAGE']._serialized_end=195
  _globals['_MESSAGE_TYPE']._serialized_start=169
  _globals['_MESSAGE_TYPE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
