# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/XTableValues.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/XTableValues.proto\x12 org.kobe.xbot.Utilities.Entities\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"S\n\x0e\x43oordinateList\x12\x41\n\x0b\x63oordinates\x18\x01 \x03(\x0b\x32,.org.kobe.xbot.Utilities.Entities.Coordinate\"\x17\n\nDoubleList\x12\t\n\x01v\x18\x01 \x03(\x01\"\x17\n\nStringList\x12\t\n\x01v\x18\x01 \x03(\t\"\x18\n\x0bIntegerList\x12\t\n\x01v\x18\x01 \x03(\x05\"\x16\n\tBytesList\x12\t\n\x01v\x18\x01 \x03(\x0c\"\x15\n\x08LongList\x12\t\n\x01v\x18\x01 \x03(\x03\"\x16\n\tFloatList\x12\t\n\x01v\x18\x01 \x03(\x02\"\x15\n\x08\x42oolList\x12\t\n\x01v\x18\x01 \x03(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.XTableValues_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COORDINATE']._serialized_start=63
  _globals['_COORDINATE']._serialized_end=97
  _globals['_COORDINATELIST']._serialized_start=99
  _globals['_COORDINATELIST']._serialized_end=182
  _globals['_DOUBLELIST']._serialized_start=184
  _globals['_DOUBLELIST']._serialized_end=207
  _globals['_STRINGLIST']._serialized_start=209
  _globals['_STRINGLIST']._serialized_end=232
  _globals['_INTEGERLIST']._serialized_start=234
  _globals['_INTEGERLIST']._serialized_end=258
  _globals['_BYTESLIST']._serialized_start=260
  _globals['_BYTESLIST']._serialized_end=282
  _globals['_LONGLIST']._serialized_start=284
  _globals['_LONGLIST']._serialized_end=305
  _globals['_FLOATLIST']._serialized_start=307
  _globals['_FLOATLIST']._serialized_end=329
  _globals['_BOOLLIST']._serialized_start=331
  _globals['_BOOLLIST']._serialized_end=352
# @@protoc_insertion_point(module_scope)
