// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/XDashDebugger.proto

// Protobuf Java Version: 3.25.6
package org.kobe.xbot.Utilities.Entities;

public final class XDashDebugger {
  private XDashDebugger() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.kobe.xbot.Utilities.Entities.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double t = 1;</code>
     * @return The t.
     */
    double getT();

    /**
     * <code>.org.kobe.xbot.Utilities.Entities.Message.Type ty = 2;</code>
     * @return The enum numeric value on the wire for ty.
     */
    int getTyValue();
    /**
     * <code>.org.kobe.xbot.Utilities.Entities.Message.Type ty = 2;</code>
     * @return The ty.
     */
    org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Type getTy();

    /**
     * <code>bytes v = 3;</code>
     * @return The v.
     */
    com.google.protobuf.ByteString getV();

    /**
     * <code>string k = 4;</code>
     * @return The k.
     */
    java.lang.String getK();
    /**
     * <code>string k = 4;</code>
     * @return The bytes for k.
     */
    com.google.protobuf.ByteString
        getKBytes();
  }
  /**
   * Protobuf type {@code org.kobe.xbot.Utilities.Entities.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.kobe.xbot.Utilities.Entities.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      ty_ = 0;
      v_ = com.google.protobuf.ByteString.EMPTY;
      k_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kobe.xbot.Utilities.Entities.XDashDebugger.internal_static_org_kobe_xbot_Utilities_Entities_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kobe.xbot.Utilities.Entities.XDashDebugger.internal_static_org_kobe_xbot_Utilities_Entities_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.class, org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code org.kobe.xbot.Utilities.Entities.Message.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>IMAGE = 0;</code>
       */
      IMAGE(0),
      /**
       * <code>LOG = 1;</code>
       */
      LOG(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>IMAGE = 0;</code>
       */
      public static final int IMAGE_VALUE = 0;
      /**
       * <code>LOG = 1;</code>
       */
      public static final int LOG_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return IMAGE;
          case 1: return LOG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.kobe.xbot.Utilities.Entities.Message.Type)
    }

    public static final int T_FIELD_NUMBER = 1;
    private double t_ = 0D;
    /**
     * <code>double t = 1;</code>
     * @return The t.
     */
    @java.lang.Override
    public double getT() {
      return t_;
    }

    public static final int TY_FIELD_NUMBER = 2;
    private int ty_ = 0;
    /**
     * <code>.org.kobe.xbot.Utilities.Entities.Message.Type ty = 2;</code>
     * @return The enum numeric value on the wire for ty.
     */
    @java.lang.Override public int getTyValue() {
      return ty_;
    }
    /**
     * <code>.org.kobe.xbot.Utilities.Entities.Message.Type ty = 2;</code>
     * @return The ty.
     */
    @java.lang.Override public org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Type getTy() {
      org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Type result = org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Type.forNumber(ty_);
      return result == null ? org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Type.UNRECOGNIZED : result;
    }

    public static final int V_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString v_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes v = 3;</code>
     * @return The v.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getV() {
      return v_;
    }

    public static final int K_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object k_ = "";
    /**
     * <code>string k = 4;</code>
     * @return The k.
     */
    @java.lang.Override
    public java.lang.String getK() {
      java.lang.Object ref = k_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        k_ = s;
        return s;
      }
    }
    /**
     * <code>string k = 4;</code>
     * @return The bytes for k.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKBytes() {
      java.lang.Object ref = k_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        k_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(t_) != 0) {
        output.writeDouble(1, t_);
      }
      if (ty_ != org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Type.IMAGE.getNumber()) {
        output.writeEnum(2, ty_);
      }
      if (!v_.isEmpty()) {
        output.writeBytes(3, v_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(k_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, k_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(t_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, t_);
      }
      if (ty_ != org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Type.IMAGE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, ty_);
      }
      if (!v_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, v_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(k_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, k_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.kobe.xbot.Utilities.Entities.XDashDebugger.Message)) {
        return super.equals(obj);
      }
      org.kobe.xbot.Utilities.Entities.XDashDebugger.Message other = (org.kobe.xbot.Utilities.Entities.XDashDebugger.Message) obj;

      if (java.lang.Double.doubleToLongBits(getT())
          != java.lang.Double.doubleToLongBits(
              other.getT())) return false;
      if (ty_ != other.ty_) return false;
      if (!getV()
          .equals(other.getV())) return false;
      if (!getK()
          .equals(other.getK())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + T_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getT()));
      hash = (37 * hash) + TY_FIELD_NUMBER;
      hash = (53 * hash) + ty_;
      hash = (37 * hash) + V_FIELD_NUMBER;
      hash = (53 * hash) + getV().hashCode();
      hash = (37 * hash) + K_FIELD_NUMBER;
      hash = (53 * hash) + getK().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.kobe.xbot.Utilities.Entities.XDashDebugger.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.kobe.xbot.Utilities.Entities.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.kobe.xbot.Utilities.Entities.Message)
        org.kobe.xbot.Utilities.Entities.XDashDebugger.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kobe.xbot.Utilities.Entities.XDashDebugger.internal_static_org_kobe_xbot_Utilities_Entities_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kobe.xbot.Utilities.Entities.XDashDebugger.internal_static_org_kobe_xbot_Utilities_Entities_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.class, org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Builder.class);
      }

      // Construct using org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        t_ = 0D;
        ty_ = 0;
        v_ = com.google.protobuf.ByteString.EMPTY;
        k_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kobe.xbot.Utilities.Entities.XDashDebugger.internal_static_org_kobe_xbot_Utilities_Entities_Message_descriptor;
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XDashDebugger.Message getDefaultInstanceForType() {
        return org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.getDefaultInstance();
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XDashDebugger.Message build() {
        org.kobe.xbot.Utilities.Entities.XDashDebugger.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XDashDebugger.Message buildPartial() {
        org.kobe.xbot.Utilities.Entities.XDashDebugger.Message result = new org.kobe.xbot.Utilities.Entities.XDashDebugger.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.kobe.xbot.Utilities.Entities.XDashDebugger.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.t_ = t_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ty_ = ty_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.v_ = v_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.k_ = k_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kobe.xbot.Utilities.Entities.XDashDebugger.Message) {
          return mergeFrom((org.kobe.xbot.Utilities.Entities.XDashDebugger.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.kobe.xbot.Utilities.Entities.XDashDebugger.Message other) {
        if (other == org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.getDefaultInstance()) return this;
        if (other.getT() != 0D) {
          setT(other.getT());
        }
        if (other.ty_ != 0) {
          setTyValue(other.getTyValue());
        }
        if (other.getV() != com.google.protobuf.ByteString.EMPTY) {
          setV(other.getV());
        }
        if (!other.getK().isEmpty()) {
          k_ = other.k_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                t_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 16: {
                ty_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                v_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                k_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double t_ ;
      /**
       * <code>double t = 1;</code>
       * @return The t.
       */
      @java.lang.Override
      public double getT() {
        return t_;
      }
      /**
       * <code>double t = 1;</code>
       * @param value The t to set.
       * @return This builder for chaining.
       */
      public Builder setT(double value) {

        t_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double t = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearT() {
        bitField0_ = (bitField0_ & ~0x00000001);
        t_ = 0D;
        onChanged();
        return this;
      }

      private int ty_ = 0;
      /**
       * <code>.org.kobe.xbot.Utilities.Entities.Message.Type ty = 2;</code>
       * @return The enum numeric value on the wire for ty.
       */
      @java.lang.Override public int getTyValue() {
        return ty_;
      }
      /**
       * <code>.org.kobe.xbot.Utilities.Entities.Message.Type ty = 2;</code>
       * @param value The enum numeric value on the wire for ty to set.
       * @return This builder for chaining.
       */
      public Builder setTyValue(int value) {
        ty_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.org.kobe.xbot.Utilities.Entities.Message.Type ty = 2;</code>
       * @return The ty.
       */
      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Type getTy() {
        org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Type result = org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Type.forNumber(ty_);
        return result == null ? org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.kobe.xbot.Utilities.Entities.Message.Type ty = 2;</code>
       * @param value The ty to set.
       * @return This builder for chaining.
       */
      public Builder setTy(org.kobe.xbot.Utilities.Entities.XDashDebugger.Message.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        ty_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.kobe.xbot.Utilities.Entities.Message.Type ty = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTy() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ty_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString v_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes v = 3;</code>
       * @return The v.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getV() {
        return v_;
      }
      /**
       * <code>bytes v = 3;</code>
       * @param value The v to set.
       * @return This builder for chaining.
       */
      public Builder setV(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        v_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes v = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearV() {
        bitField0_ = (bitField0_ & ~0x00000004);
        v_ = getDefaultInstance().getV();
        onChanged();
        return this;
      }

      private java.lang.Object k_ = "";
      /**
       * <code>string k = 4;</code>
       * @return The k.
       */
      public java.lang.String getK() {
        java.lang.Object ref = k_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          k_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string k = 4;</code>
       * @return The bytes for k.
       */
      public com.google.protobuf.ByteString
          getKBytes() {
        java.lang.Object ref = k_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          k_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string k = 4;</code>
       * @param value The k to set.
       * @return This builder for chaining.
       */
      public Builder setK(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        k_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string k = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearK() {
        k_ = getDefaultInstance().getK();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string k = 4;</code>
       * @param value The bytes for k to set.
       * @return This builder for chaining.
       */
      public Builder setKBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        k_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.kobe.xbot.Utilities.Entities.Message)
    }

    // @@protoc_insertion_point(class_scope:org.kobe.xbot.Utilities.Entities.Message)
    private static final org.kobe.xbot.Utilities.Entities.XDashDebugger.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.kobe.xbot.Utilities.Entities.XDashDebugger.Message();
    }

    public static org.kobe.xbot.Utilities.Entities.XDashDebugger.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.kobe.xbot.Utilities.Entities.XDashDebugger.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_kobe_xbot_Utilities_Entities_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_kobe_xbot_Utilities_Entities_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032protos/XDashDebugger.proto\022 org.kobe.x" +
      "bot.Utilities.Entities\"\202\001\n\007Message\022\t\n\001t\030" +
      "\001 \001(\001\022:\n\002ty\030\002 \001(\0162..org.kobe.xbot.Utilit" +
      "ies.Entities.Message.Type\022\t\n\001v\030\003 \001(\014\022\t\n\001" +
      "k\030\004 \001(\t\"\032\n\004Type\022\t\n\005IMAGE\020\000\022\007\n\003LOG\020\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_kobe_xbot_Utilities_Entities_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_kobe_xbot_Utilities_Entities_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_kobe_xbot_Utilities_Entities_Message_descriptor,
        new java.lang.String[] { "T", "Ty", "V", "K", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
