package org.kobe.xbot.Utilities.Entities;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: XTableClientStatistics.proto
// Protobuf Java Version: 4.29.2

public final class XTableClientStatistics {
  private XTableClientStatistics() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      XTableClientStatistics.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Enum representing health status.
   * </pre>
   *
   * Protobuf enum {@code HealthStatus}
   */
  public enum HealthStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GOOD = 0;</code>
     */
    GOOD(0),
    /**
     * <code>OKAY = 1;</code>
     */
    OKAY(1),
    /**
     * <code>STRESSED = 2;</code>
     */
    STRESSED(2),
    /**
     * <code>OVERLOAD = 3;</code>
     */
    OVERLOAD(3),
    /**
     * <code>CRITICAL = 4;</code>
     */
    CRITICAL(4),
    /**
     * <code>UNKNOWN = 5;</code>
     */
    UNKNOWN(5),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        HealthStatus.class.getName());
    }
    /**
     * <code>GOOD = 0;</code>
     */
    public static final int GOOD_VALUE = 0;
    /**
     * <code>OKAY = 1;</code>
     */
    public static final int OKAY_VALUE = 1;
    /**
     * <code>STRESSED = 2;</code>
     */
    public static final int STRESSED_VALUE = 2;
    /**
     * <code>OVERLOAD = 3;</code>
     */
    public static final int OVERLOAD_VALUE = 3;
    /**
     * <code>CRITICAL = 4;</code>
     */
    public static final int CRITICAL_VALUE = 4;
    /**
     * <code>UNKNOWN = 5;</code>
     */
    public static final int UNKNOWN_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HealthStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static HealthStatus forNumber(int value) {
      switch (value) {
        case 0: return GOOD;
        case 1: return OKAY;
        case 2: return STRESSED;
        case 3: return OVERLOAD;
        case 4: return CRITICAL;
        case 5: return UNKNOWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HealthStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HealthStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HealthStatus>() {
            public HealthStatus findValueByNumber(int number) {
              return HealthStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return XTableClientStatistics.getDescriptor().getEnumTypes().get(0);
    }

    private static final HealthStatus[] VALUES = values();

    public static HealthStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HealthStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:HealthStatus)
  }

  public interface ClientStatisticsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientStatistics)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 nano_time = 1;</code>
     * @return The nanoTime.
     */
    long getNanoTime();

    /**
     * <code>int64 max_memory_mb = 2;</code>
     * @return The maxMemoryMb.
     */
    long getMaxMemoryMb();

    /**
     * <code>int64 free_memory_mb = 3;</code>
     * @return The freeMemoryMb.
     */
    long getFreeMemoryMb();

    /**
     * <code>int64 used_memory_mb = 4;</code>
     * @return The usedMemoryMb.
     */
    long getUsedMemoryMb();

    /**
     * <code>double process_cpu_load_percentage = 5;</code>
     * @return The processCpuLoadPercentage.
     */
    double getProcessCpuLoadPercentage();

    /**
     * <code>int32 available_processors = 6;</code>
     * @return The availableProcessors.
     */
    int getAvailableProcessors();

    /**
     * <code>int64 total_threads = 7;</code>
     * @return The totalThreads.
     */
    long getTotalThreads();

    /**
     * <code>string ip = 8;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 8;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>string hostname = 9;</code>
     * @return The hostname.
     */
    java.lang.String getHostname();
    /**
     * <code>string hostname = 9;</code>
     * @return The bytes for hostname.
     */
    com.google.protobuf.ByteString
        getHostnameBytes();

    /**
     * <code>string process_id = 10;</code>
     * @return The processId.
     */
    java.lang.String getProcessId();
    /**
     * <code>string process_id = 10;</code>
     * @return The bytes for processId.
     */
    com.google.protobuf.ByteString
        getProcessIdBytes();

    /**
     * <code>string lang_version = 11;</code>
     * @return The langVersion.
     */
    java.lang.String getLangVersion();
    /**
     * <code>string lang_version = 11;</code>
     * @return The bytes for langVersion.
     */
    com.google.protobuf.ByteString
        getLangVersionBytes();

    /**
     * <code>string lang_vendor = 12;</code>
     * @return The langVendor.
     */
    java.lang.String getLangVendor();
    /**
     * <code>string lang_vendor = 12;</code>
     * @return The bytes for langVendor.
     */
    com.google.protobuf.ByteString
        getLangVendorBytes();

    /**
     * <code>string jvm_name = 13;</code>
     * @return The jvmName.
     */
    java.lang.String getJvmName();
    /**
     * <code>string jvm_name = 13;</code>
     * @return The bytes for jvmName.
     */
    com.google.protobuf.ByteString
        getJvmNameBytes();

    /**
     * <code>.HealthStatus health = 14;</code>
     * @return The enum numeric value on the wire for health.
     */
    int getHealthValue();
    /**
     * <code>.HealthStatus health = 14;</code>
     * @return The health.
     */
    XTableClientStatistics.HealthStatus getHealth();

    /**
     * <pre>
     * Optional fields
     * </pre>
     *
     * <code>optional string version = 15;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <pre>
     * Optional fields
     * </pre>
     *
     * <code>optional string version = 15;</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <pre>
     * Optional fields
     * </pre>
     *
     * <code>optional string version = 15;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>optional string type = 16;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional string type = 16;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 16;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional string uuid = 17;</code>
     * @return Whether the uuid field is set.
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 17;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 17;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional int32 buffer_size = 18;</code>
     * @return Whether the bufferSize field is set.
     */
    boolean hasBufferSize();
    /**
     * <code>optional int32 buffer_size = 18;</code>
     * @return The bufferSize.
     */
    int getBufferSize();

    /**
     * <code>optional int32 max_buffer_size = 19;</code>
     * @return Whether the maxBufferSize field is set.
     */
    boolean hasMaxBufferSize();
    /**
     * <code>optional int32 max_buffer_size = 19;</code>
     * @return The maxBufferSize.
     */
    int getMaxBufferSize();
  }
  /**
   * <pre>
   * Message representing client statistics.
   * </pre>
   *
   * Protobuf type {@code ClientStatistics}
   */
  public static final class ClientStatistics extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ClientStatistics)
      ClientStatisticsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        ClientStatistics.class.getName());
    }
    // Use ClientStatistics.newBuilder() to construct.
    private ClientStatistics(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ClientStatistics() {
      ip_ = "";
      hostname_ = "";
      processId_ = "";
      langVersion_ = "";
      langVendor_ = "";
      jvmName_ = "";
      health_ = 0;
      version_ = "";
      type_ = "";
      uuid_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return XTableClientStatistics.internal_static_ClientStatistics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return XTableClientStatistics.internal_static_ClientStatistics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              XTableClientStatistics.ClientStatistics.class, XTableClientStatistics.ClientStatistics.Builder.class);
    }

    private int bitField0_;
    public static final int NANO_TIME_FIELD_NUMBER = 1;
    private long nanoTime_ = 0L;
    /**
     * <code>int64 nano_time = 1;</code>
     * @return The nanoTime.
     */
    @java.lang.Override
    public long getNanoTime() {
      return nanoTime_;
    }

    public static final int MAX_MEMORY_MB_FIELD_NUMBER = 2;
    private long maxMemoryMb_ = 0L;
    /**
     * <code>int64 max_memory_mb = 2;</code>
     * @return The maxMemoryMb.
     */
    @java.lang.Override
    public long getMaxMemoryMb() {
      return maxMemoryMb_;
    }

    public static final int FREE_MEMORY_MB_FIELD_NUMBER = 3;
    private long freeMemoryMb_ = 0L;
    /**
     * <code>int64 free_memory_mb = 3;</code>
     * @return The freeMemoryMb.
     */
    @java.lang.Override
    public long getFreeMemoryMb() {
      return freeMemoryMb_;
    }

    public static final int USED_MEMORY_MB_FIELD_NUMBER = 4;
    private long usedMemoryMb_ = 0L;
    /**
     * <code>int64 used_memory_mb = 4;</code>
     * @return The usedMemoryMb.
     */
    @java.lang.Override
    public long getUsedMemoryMb() {
      return usedMemoryMb_;
    }

    public static final int PROCESS_CPU_LOAD_PERCENTAGE_FIELD_NUMBER = 5;
    private double processCpuLoadPercentage_ = 0D;
    /**
     * <code>double process_cpu_load_percentage = 5;</code>
     * @return The processCpuLoadPercentage.
     */
    @java.lang.Override
    public double getProcessCpuLoadPercentage() {
      return processCpuLoadPercentage_;
    }

    public static final int AVAILABLE_PROCESSORS_FIELD_NUMBER = 6;
    private int availableProcessors_ = 0;
    /**
     * <code>int32 available_processors = 6;</code>
     * @return The availableProcessors.
     */
    @java.lang.Override
    public int getAvailableProcessors() {
      return availableProcessors_;
    }

    public static final int TOTAL_THREADS_FIELD_NUMBER = 7;
    private long totalThreads_ = 0L;
    /**
     * <code>int64 total_threads = 7;</code>
     * @return The totalThreads.
     */
    @java.lang.Override
    public long getTotalThreads() {
      return totalThreads_;
    }

    public static final int IP_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object ip_ = "";
    /**
     * <code>string ip = 8;</code>
     * @return The ip.
     */
    @java.lang.Override
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 8;</code>
     * @return The bytes for ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOSTNAME_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object hostname_ = "";
    /**
     * <code>string hostname = 9;</code>
     * @return The hostname.
     */
    @java.lang.Override
    public java.lang.String getHostname() {
      java.lang.Object ref = hostname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostname_ = s;
        return s;
      }
    }
    /**
     * <code>string hostname = 9;</code>
     * @return The bytes for hostname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROCESS_ID_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object processId_ = "";
    /**
     * <code>string process_id = 10;</code>
     * @return The processId.
     */
    @java.lang.Override
    public java.lang.String getProcessId() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processId_ = s;
        return s;
      }
    }
    /**
     * <code>string process_id = 10;</code>
     * @return The bytes for processId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProcessIdBytes() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANG_VERSION_FIELD_NUMBER = 11;
    @SuppressWarnings("serial")
    private volatile java.lang.Object langVersion_ = "";
    /**
     * <code>string lang_version = 11;</code>
     * @return The langVersion.
     */
    @java.lang.Override
    public java.lang.String getLangVersion() {
      java.lang.Object ref = langVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        langVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string lang_version = 11;</code>
     * @return The bytes for langVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLangVersionBytes() {
      java.lang.Object ref = langVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        langVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANG_VENDOR_FIELD_NUMBER = 12;
    @SuppressWarnings("serial")
    private volatile java.lang.Object langVendor_ = "";
    /**
     * <code>string lang_vendor = 12;</code>
     * @return The langVendor.
     */
    @java.lang.Override
    public java.lang.String getLangVendor() {
      java.lang.Object ref = langVendor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        langVendor_ = s;
        return s;
      }
    }
    /**
     * <code>string lang_vendor = 12;</code>
     * @return The bytes for langVendor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLangVendorBytes() {
      java.lang.Object ref = langVendor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        langVendor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JVM_NAME_FIELD_NUMBER = 13;
    @SuppressWarnings("serial")
    private volatile java.lang.Object jvmName_ = "";
    /**
     * <code>string jvm_name = 13;</code>
     * @return The jvmName.
     */
    @java.lang.Override
    public java.lang.String getJvmName() {
      java.lang.Object ref = jvmName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jvmName_ = s;
        return s;
      }
    }
    /**
     * <code>string jvm_name = 13;</code>
     * @return The bytes for jvmName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJvmNameBytes() {
      java.lang.Object ref = jvmName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jvmName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEALTH_FIELD_NUMBER = 14;
    private int health_ = 0;
    /**
     * <code>.HealthStatus health = 14;</code>
     * @return The enum numeric value on the wire for health.
     */
    @java.lang.Override public int getHealthValue() {
      return health_;
    }
    /**
     * <code>.HealthStatus health = 14;</code>
     * @return The health.
     */
    @java.lang.Override public XTableClientStatistics.HealthStatus getHealth() {
      XTableClientStatistics.HealthStatus result = XTableClientStatistics.HealthStatus.forNumber(health_);
      return result == null ? XTableClientStatistics.HealthStatus.UNRECOGNIZED : result;
    }

    public static final int VERSION_FIELD_NUMBER = 15;
    @SuppressWarnings("serial")
    private volatile java.lang.Object version_ = "";
    /**
     * <pre>
     * Optional fields
     * </pre>
     *
     * <code>optional string version = 15;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Optional fields
     * </pre>
     *
     * <code>optional string version = 15;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional fields
     * </pre>
     *
     * <code>optional string version = 15;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 16;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <code>optional string type = 16;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string type = 16;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>optional string type = 16;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UUID_FIELD_NUMBER = 17;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uuid_ = "";
    /**
     * <code>optional string uuid = 17;</code>
     * @return Whether the uuid field is set.
     */
    @java.lang.Override
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string uuid = 17;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string uuid = 17;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUFFER_SIZE_FIELD_NUMBER = 18;
    private int bufferSize_ = 0;
    /**
     * <code>optional int32 buffer_size = 18;</code>
     * @return Whether the bufferSize field is set.
     */
    @java.lang.Override
    public boolean hasBufferSize() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 buffer_size = 18;</code>
     * @return The bufferSize.
     */
    @java.lang.Override
    public int getBufferSize() {
      return bufferSize_;
    }

    public static final int MAX_BUFFER_SIZE_FIELD_NUMBER = 19;
    private int maxBufferSize_ = 0;
    /**
     * <code>optional int32 max_buffer_size = 19;</code>
     * @return Whether the maxBufferSize field is set.
     */
    @java.lang.Override
    public boolean hasMaxBufferSize() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 max_buffer_size = 19;</code>
     * @return The maxBufferSize.
     */
    @java.lang.Override
    public int getMaxBufferSize() {
      return maxBufferSize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nanoTime_ != 0L) {
        output.writeInt64(1, nanoTime_);
      }
      if (maxMemoryMb_ != 0L) {
        output.writeInt64(2, maxMemoryMb_);
      }
      if (freeMemoryMb_ != 0L) {
        output.writeInt64(3, freeMemoryMb_);
      }
      if (usedMemoryMb_ != 0L) {
        output.writeInt64(4, usedMemoryMb_);
      }
      if (java.lang.Double.doubleToRawLongBits(processCpuLoadPercentage_) != 0) {
        output.writeDouble(5, processCpuLoadPercentage_);
      }
      if (availableProcessors_ != 0) {
        output.writeInt32(6, availableProcessors_);
      }
      if (totalThreads_ != 0L) {
        output.writeInt64(7, totalThreads_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ip_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, ip_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hostname_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, hostname_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(processId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, processId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(langVersion_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 11, langVersion_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(langVendor_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 12, langVendor_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jvmName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 13, jvmName_);
      }
      if (health_ != XTableClientStatistics.HealthStatus.GOOD.getNumber()) {
        output.writeEnum(14, health_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 15, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 16, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 17, uuid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(18, bufferSize_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(19, maxBufferSize_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nanoTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nanoTime_);
      }
      if (maxMemoryMb_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, maxMemoryMb_);
      }
      if (freeMemoryMb_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, freeMemoryMb_);
      }
      if (usedMemoryMb_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, usedMemoryMb_);
      }
      if (java.lang.Double.doubleToRawLongBits(processCpuLoadPercentage_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, processCpuLoadPercentage_);
      }
      if (availableProcessors_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, availableProcessors_);
      }
      if (totalThreads_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, totalThreads_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ip_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, ip_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hostname_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, hostname_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(processId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, processId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(langVersion_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(11, langVersion_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(langVendor_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(12, langVendor_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jvmName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(13, jvmName_);
      }
      if (health_ != XTableClientStatistics.HealthStatus.GOOD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(14, health_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(15, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(16, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(17, uuid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, bufferSize_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, maxBufferSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof XTableClientStatistics.ClientStatistics)) {
        return super.equals(obj);
      }
      XTableClientStatistics.ClientStatistics other = (XTableClientStatistics.ClientStatistics) obj;

      if (getNanoTime()
          != other.getNanoTime()) return false;
      if (getMaxMemoryMb()
          != other.getMaxMemoryMb()) return false;
      if (getFreeMemoryMb()
          != other.getFreeMemoryMb()) return false;
      if (getUsedMemoryMb()
          != other.getUsedMemoryMb()) return false;
      if (java.lang.Double.doubleToLongBits(getProcessCpuLoadPercentage())
          != java.lang.Double.doubleToLongBits(
              other.getProcessCpuLoadPercentage())) return false;
      if (getAvailableProcessors()
          != other.getAvailableProcessors()) return false;
      if (getTotalThreads()
          != other.getTotalThreads()) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (!getHostname()
          .equals(other.getHostname())) return false;
      if (!getProcessId()
          .equals(other.getProcessId())) return false;
      if (!getLangVersion()
          .equals(other.getLangVersion())) return false;
      if (!getLangVendor()
          .equals(other.getLangVendor())) return false;
      if (!getJvmName()
          .equals(other.getJvmName())) return false;
      if (health_ != other.health_) return false;
      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (!getVersion()
            .equals(other.getVersion())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (hasUuid() != other.hasUuid()) return false;
      if (hasUuid()) {
        if (!getUuid()
            .equals(other.getUuid())) return false;
      }
      if (hasBufferSize() != other.hasBufferSize()) return false;
      if (hasBufferSize()) {
        if (getBufferSize()
            != other.getBufferSize()) return false;
      }
      if (hasMaxBufferSize() != other.hasMaxBufferSize()) return false;
      if (hasMaxBufferSize()) {
        if (getMaxBufferSize()
            != other.getMaxBufferSize()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NANO_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNanoTime());
      hash = (37 * hash) + MAX_MEMORY_MB_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMaxMemoryMb());
      hash = (37 * hash) + FREE_MEMORY_MB_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFreeMemoryMb());
      hash = (37 * hash) + USED_MEMORY_MB_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUsedMemoryMb());
      hash = (37 * hash) + PROCESS_CPU_LOAD_PERCENTAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getProcessCpuLoadPercentage()));
      hash = (37 * hash) + AVAILABLE_PROCESSORS_FIELD_NUMBER;
      hash = (53 * hash) + getAvailableProcessors();
      hash = (37 * hash) + TOTAL_THREADS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalThreads());
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHostname().hashCode();
      hash = (37 * hash) + PROCESS_ID_FIELD_NUMBER;
      hash = (53 * hash) + getProcessId().hashCode();
      hash = (37 * hash) + LANG_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getLangVersion().hashCode();
      hash = (37 * hash) + LANG_VENDOR_FIELD_NUMBER;
      hash = (53 * hash) + getLangVendor().hashCode();
      hash = (37 * hash) + JVM_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getJvmName().hashCode();
      hash = (37 * hash) + HEALTH_FIELD_NUMBER;
      hash = (53 * hash) + health_;
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      if (hasBufferSize()) {
        hash = (37 * hash) + BUFFER_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getBufferSize();
      }
      if (hasMaxBufferSize()) {
        hash = (37 * hash) + MAX_BUFFER_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getMaxBufferSize();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static XTableClientStatistics.ClientStatistics parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static XTableClientStatistics.ClientStatistics parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static XTableClientStatistics.ClientStatistics parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static XTableClientStatistics.ClientStatistics parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static XTableClientStatistics.ClientStatistics parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static XTableClientStatistics.ClientStatistics parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static XTableClientStatistics.ClientStatistics parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static XTableClientStatistics.ClientStatistics parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static XTableClientStatistics.ClientStatistics parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static XTableClientStatistics.ClientStatistics parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static XTableClientStatistics.ClientStatistics parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static XTableClientStatistics.ClientStatistics parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(XTableClientStatistics.ClientStatistics prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message representing client statistics.
     * </pre>
     *
     * Protobuf type {@code ClientStatistics}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientStatistics)
        XTableClientStatistics.ClientStatisticsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return XTableClientStatistics.internal_static_ClientStatistics_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return XTableClientStatistics.internal_static_ClientStatistics_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                XTableClientStatistics.ClientStatistics.class, XTableClientStatistics.ClientStatistics.Builder.class);
      }

      // Construct using XTableClientStatistics.ClientStatistics.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nanoTime_ = 0L;
        maxMemoryMb_ = 0L;
        freeMemoryMb_ = 0L;
        usedMemoryMb_ = 0L;
        processCpuLoadPercentage_ = 0D;
        availableProcessors_ = 0;
        totalThreads_ = 0L;
        ip_ = "";
        hostname_ = "";
        processId_ = "";
        langVersion_ = "";
        langVendor_ = "";
        jvmName_ = "";
        health_ = 0;
        version_ = "";
        type_ = "";
        uuid_ = "";
        bufferSize_ = 0;
        maxBufferSize_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return XTableClientStatistics.internal_static_ClientStatistics_descriptor;
      }

      @java.lang.Override
      public XTableClientStatistics.ClientStatistics getDefaultInstanceForType() {
        return XTableClientStatistics.ClientStatistics.getDefaultInstance();
      }

      @java.lang.Override
      public XTableClientStatistics.ClientStatistics build() {
        XTableClientStatistics.ClientStatistics result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public XTableClientStatistics.ClientStatistics buildPartial() {
        XTableClientStatistics.ClientStatistics result = new XTableClientStatistics.ClientStatistics(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(XTableClientStatistics.ClientStatistics result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nanoTime_ = nanoTime_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.maxMemoryMb_ = maxMemoryMb_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.freeMemoryMb_ = freeMemoryMb_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.usedMemoryMb_ = usedMemoryMb_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.processCpuLoadPercentage_ = processCpuLoadPercentage_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.availableProcessors_ = availableProcessors_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.totalThreads_ = totalThreads_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.ip_ = ip_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.hostname_ = hostname_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.processId_ = processId_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.langVersion_ = langVersion_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.langVendor_ = langVendor_;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.jvmName_ = jvmName_;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.health_ = health_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00008000) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00010000) != 0)) {
          result.uuid_ = uuid_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00020000) != 0)) {
          result.bufferSize_ = bufferSize_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00040000) != 0)) {
          result.maxBufferSize_ = maxBufferSize_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof XTableClientStatistics.ClientStatistics) {
          return mergeFrom((XTableClientStatistics.ClientStatistics)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(XTableClientStatistics.ClientStatistics other) {
        if (other == XTableClientStatistics.ClientStatistics.getDefaultInstance()) return this;
        if (other.getNanoTime() != 0L) {
          setNanoTime(other.getNanoTime());
        }
        if (other.getMaxMemoryMb() != 0L) {
          setMaxMemoryMb(other.getMaxMemoryMb());
        }
        if (other.getFreeMemoryMb() != 0L) {
          setFreeMemoryMb(other.getFreeMemoryMb());
        }
        if (other.getUsedMemoryMb() != 0L) {
          setUsedMemoryMb(other.getUsedMemoryMb());
        }
        if (other.getProcessCpuLoadPercentage() != 0D) {
          setProcessCpuLoadPercentage(other.getProcessCpuLoadPercentage());
        }
        if (other.getAvailableProcessors() != 0) {
          setAvailableProcessors(other.getAvailableProcessors());
        }
        if (other.getTotalThreads() != 0L) {
          setTotalThreads(other.getTotalThreads());
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (!other.getHostname().isEmpty()) {
          hostname_ = other.hostname_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        if (!other.getProcessId().isEmpty()) {
          processId_ = other.processId_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (!other.getLangVersion().isEmpty()) {
          langVersion_ = other.langVersion_;
          bitField0_ |= 0x00000400;
          onChanged();
        }
        if (!other.getLangVendor().isEmpty()) {
          langVendor_ = other.langVendor_;
          bitField0_ |= 0x00000800;
          onChanged();
        }
        if (!other.getJvmName().isEmpty()) {
          jvmName_ = other.jvmName_;
          bitField0_ |= 0x00001000;
          onChanged();
        }
        if (other.health_ != 0) {
          setHealthValue(other.getHealthValue());
        }
        if (other.hasVersion()) {
          version_ = other.version_;
          bitField0_ |= 0x00004000;
          onChanged();
        }
        if (other.hasType()) {
          type_ = other.type_;
          bitField0_ |= 0x00008000;
          onChanged();
        }
        if (other.hasUuid()) {
          uuid_ = other.uuid_;
          bitField0_ |= 0x00010000;
          onChanged();
        }
        if (other.hasBufferSize()) {
          setBufferSize(other.getBufferSize());
        }
        if (other.hasMaxBufferSize()) {
          setMaxBufferSize(other.getMaxBufferSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                nanoTime_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                maxMemoryMb_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                freeMemoryMb_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                usedMemoryMb_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 41: {
                processCpuLoadPercentage_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 48: {
                availableProcessors_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                totalThreads_ = input.readInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                ip_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                hostname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                processId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 90: {
                langVersion_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000400;
                break;
              } // case 90
              case 98: {
                langVendor_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000800;
                break;
              } // case 98
              case 106: {
                jvmName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00001000;
                break;
              } // case 106
              case 112: {
                health_ = input.readEnum();
                bitField0_ |= 0x00002000;
                break;
              } // case 112
              case 122: {
                version_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00004000;
                break;
              } // case 122
              case 130: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00008000;
                break;
              } // case 130
              case 138: {
                uuid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00010000;
                break;
              } // case 138
              case 144: {
                bufferSize_ = input.readInt32();
                bitField0_ |= 0x00020000;
                break;
              } // case 144
              case 152: {
                maxBufferSize_ = input.readInt32();
                bitField0_ |= 0x00040000;
                break;
              } // case 152
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long nanoTime_ ;
      /**
       * <code>int64 nano_time = 1;</code>
       * @return The nanoTime.
       */
      @java.lang.Override
      public long getNanoTime() {
        return nanoTime_;
      }
      /**
       * <code>int64 nano_time = 1;</code>
       * @param value The nanoTime to set.
       * @return This builder for chaining.
       */
      public Builder setNanoTime(long value) {

        nanoTime_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 nano_time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNanoTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nanoTime_ = 0L;
        onChanged();
        return this;
      }

      private long maxMemoryMb_ ;
      /**
       * <code>int64 max_memory_mb = 2;</code>
       * @return The maxMemoryMb.
       */
      @java.lang.Override
      public long getMaxMemoryMb() {
        return maxMemoryMb_;
      }
      /**
       * <code>int64 max_memory_mb = 2;</code>
       * @param value The maxMemoryMb to set.
       * @return This builder for chaining.
       */
      public Builder setMaxMemoryMb(long value) {

        maxMemoryMb_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 max_memory_mb = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxMemoryMb() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxMemoryMb_ = 0L;
        onChanged();
        return this;
      }

      private long freeMemoryMb_ ;
      /**
       * <code>int64 free_memory_mb = 3;</code>
       * @return The freeMemoryMb.
       */
      @java.lang.Override
      public long getFreeMemoryMb() {
        return freeMemoryMb_;
      }
      /**
       * <code>int64 free_memory_mb = 3;</code>
       * @param value The freeMemoryMb to set.
       * @return This builder for chaining.
       */
      public Builder setFreeMemoryMb(long value) {

        freeMemoryMb_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 free_memory_mb = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFreeMemoryMb() {
        bitField0_ = (bitField0_ & ~0x00000004);
        freeMemoryMb_ = 0L;
        onChanged();
        return this;
      }

      private long usedMemoryMb_ ;
      /**
       * <code>int64 used_memory_mb = 4;</code>
       * @return The usedMemoryMb.
       */
      @java.lang.Override
      public long getUsedMemoryMb() {
        return usedMemoryMb_;
      }
      /**
       * <code>int64 used_memory_mb = 4;</code>
       * @param value The usedMemoryMb to set.
       * @return This builder for chaining.
       */
      public Builder setUsedMemoryMb(long value) {

        usedMemoryMb_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 used_memory_mb = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsedMemoryMb() {
        bitField0_ = (bitField0_ & ~0x00000008);
        usedMemoryMb_ = 0L;
        onChanged();
        return this;
      }

      private double processCpuLoadPercentage_ ;
      /**
       * <code>double process_cpu_load_percentage = 5;</code>
       * @return The processCpuLoadPercentage.
       */
      @java.lang.Override
      public double getProcessCpuLoadPercentage() {
        return processCpuLoadPercentage_;
      }
      /**
       * <code>double process_cpu_load_percentage = 5;</code>
       * @param value The processCpuLoadPercentage to set.
       * @return This builder for chaining.
       */
      public Builder setProcessCpuLoadPercentage(double value) {

        processCpuLoadPercentage_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double process_cpu_load_percentage = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearProcessCpuLoadPercentage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        processCpuLoadPercentage_ = 0D;
        onChanged();
        return this;
      }

      private int availableProcessors_ ;
      /**
       * <code>int32 available_processors = 6;</code>
       * @return The availableProcessors.
       */
      @java.lang.Override
      public int getAvailableProcessors() {
        return availableProcessors_;
      }
      /**
       * <code>int32 available_processors = 6;</code>
       * @param value The availableProcessors to set.
       * @return This builder for chaining.
       */
      public Builder setAvailableProcessors(int value) {

        availableProcessors_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 available_processors = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvailableProcessors() {
        bitField0_ = (bitField0_ & ~0x00000020);
        availableProcessors_ = 0;
        onChanged();
        return this;
      }

      private long totalThreads_ ;
      /**
       * <code>int64 total_threads = 7;</code>
       * @return The totalThreads.
       */
      @java.lang.Override
      public long getTotalThreads() {
        return totalThreads_;
      }
      /**
       * <code>int64 total_threads = 7;</code>
       * @param value The totalThreads to set.
       * @return This builder for chaining.
       */
      public Builder setTotalThreads(long value) {

        totalThreads_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int64 total_threads = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalThreads() {
        bitField0_ = (bitField0_ & ~0x00000040);
        totalThreads_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 8;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 8;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 8;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ip_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        ip_ = getDefaultInstance().getIp();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 8;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ip_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.lang.Object hostname_ = "";
      /**
       * <code>string hostname = 9;</code>
       * @return The hostname.
       */
      public java.lang.String getHostname() {
        java.lang.Object ref = hostname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hostname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hostname = 9;</code>
       * @return The bytes for hostname.
       */
      public com.google.protobuf.ByteString
          getHostnameBytes() {
        java.lang.Object ref = hostname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hostname = 9;</code>
       * @param value The hostname to set.
       * @return This builder for chaining.
       */
      public Builder setHostname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        hostname_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>string hostname = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearHostname() {
        hostname_ = getDefaultInstance().getHostname();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>string hostname = 9;</code>
       * @param value The bytes for hostname to set.
       * @return This builder for chaining.
       */
      public Builder setHostnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        hostname_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private java.lang.Object processId_ = "";
      /**
       * <code>string process_id = 10;</code>
       * @return The processId.
       */
      public java.lang.String getProcessId() {
        java.lang.Object ref = processId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          processId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string process_id = 10;</code>
       * @return The bytes for processId.
       */
      public com.google.protobuf.ByteString
          getProcessIdBytes() {
        java.lang.Object ref = processId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          processId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string process_id = 10;</code>
       * @param value The processId to set.
       * @return This builder for chaining.
       */
      public Builder setProcessId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        processId_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>string process_id = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearProcessId() {
        processId_ = getDefaultInstance().getProcessId();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>string process_id = 10;</code>
       * @param value The bytes for processId to set.
       * @return This builder for chaining.
       */
      public Builder setProcessIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        processId_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private java.lang.Object langVersion_ = "";
      /**
       * <code>string lang_version = 11;</code>
       * @return The langVersion.
       */
      public java.lang.String getLangVersion() {
        java.lang.Object ref = langVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          langVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lang_version = 11;</code>
       * @return The bytes for langVersion.
       */
      public com.google.protobuf.ByteString
          getLangVersionBytes() {
        java.lang.Object ref = langVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          langVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lang_version = 11;</code>
       * @param value The langVersion to set.
       * @return This builder for chaining.
       */
      public Builder setLangVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        langVersion_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>string lang_version = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearLangVersion() {
        langVersion_ = getDefaultInstance().getLangVersion();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <code>string lang_version = 11;</code>
       * @param value The bytes for langVersion to set.
       * @return This builder for chaining.
       */
      public Builder setLangVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        langVersion_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }

      private java.lang.Object langVendor_ = "";
      /**
       * <code>string lang_vendor = 12;</code>
       * @return The langVendor.
       */
      public java.lang.String getLangVendor() {
        java.lang.Object ref = langVendor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          langVendor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lang_vendor = 12;</code>
       * @return The bytes for langVendor.
       */
      public com.google.protobuf.ByteString
          getLangVendorBytes() {
        java.lang.Object ref = langVendor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          langVendor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lang_vendor = 12;</code>
       * @param value The langVendor to set.
       * @return This builder for chaining.
       */
      public Builder setLangVendor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        langVendor_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>string lang_vendor = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearLangVendor() {
        langVendor_ = getDefaultInstance().getLangVendor();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
        return this;
      }
      /**
       * <code>string lang_vendor = 12;</code>
       * @param value The bytes for langVendor to set.
       * @return This builder for chaining.
       */
      public Builder setLangVendorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        langVendor_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }

      private java.lang.Object jvmName_ = "";
      /**
       * <code>string jvm_name = 13;</code>
       * @return The jvmName.
       */
      public java.lang.String getJvmName() {
        java.lang.Object ref = jvmName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jvmName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string jvm_name = 13;</code>
       * @return The bytes for jvmName.
       */
      public com.google.protobuf.ByteString
          getJvmNameBytes() {
        java.lang.Object ref = jvmName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jvmName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string jvm_name = 13;</code>
       * @param value The jvmName to set.
       * @return This builder for chaining.
       */
      public Builder setJvmName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        jvmName_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>string jvm_name = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearJvmName() {
        jvmName_ = getDefaultInstance().getJvmName();
        bitField0_ = (bitField0_ & ~0x00001000);
        onChanged();
        return this;
      }
      /**
       * <code>string jvm_name = 13;</code>
       * @param value The bytes for jvmName to set.
       * @return This builder for chaining.
       */
      public Builder setJvmNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        jvmName_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }

      private int health_ = 0;
      /**
       * <code>.HealthStatus health = 14;</code>
       * @return The enum numeric value on the wire for health.
       */
      @java.lang.Override public int getHealthValue() {
        return health_;
      }
      /**
       * <code>.HealthStatus health = 14;</code>
       * @param value The enum numeric value on the wire for health to set.
       * @return This builder for chaining.
       */
      public Builder setHealthValue(int value) {
        health_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <code>.HealthStatus health = 14;</code>
       * @return The health.
       */
      @java.lang.Override
      public XTableClientStatistics.HealthStatus getHealth() {
        XTableClientStatistics.HealthStatus result = XTableClientStatistics.HealthStatus.forNumber(health_);
        return result == null ? XTableClientStatistics.HealthStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.HealthStatus health = 14;</code>
       * @param value The health to set.
       * @return This builder for chaining.
       */
      public Builder setHealth(XTableClientStatistics.HealthStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00002000;
        health_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.HealthStatus health = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearHealth() {
        bitField0_ = (bitField0_ & ~0x00002000);
        health_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <pre>
       * Optional fields
       * </pre>
       *
       * <code>optional string version = 15;</code>
       * @return Whether the version field is set.
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00004000) != 0);
      }
      /**
       * <pre>
       * Optional fields
       * </pre>
       *
       * <code>optional string version = 15;</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional fields
       * </pre>
       *
       * <code>optional string version = 15;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional fields
       * </pre>
       *
       * <code>optional string version = 15;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        version_ = value;
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional fields
       * </pre>
       *
       * <code>optional string version = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        version_ = getDefaultInstance().getVersion();
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional fields
       * </pre>
       *
       * <code>optional string version = 15;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        version_ = value;
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 16;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00008000) != 0);
      }
      /**
       * <code>optional string type = 16;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 16;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 16;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00008000;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00008000);
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 16;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00008000;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 17;</code>
       * @return Whether the uuid field is set.
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00010000) != 0);
      }
      /**
       * <code>optional string uuid = 17;</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 17;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 17;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uuid_ = value;
        bitField0_ |= 0x00010000;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        uuid_ = getDefaultInstance().getUuid();
        bitField0_ = (bitField0_ & ~0x00010000);
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 17;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uuid_ = value;
        bitField0_ |= 0x00010000;
        onChanged();
        return this;
      }

      private int bufferSize_ ;
      /**
       * <code>optional int32 buffer_size = 18;</code>
       * @return Whether the bufferSize field is set.
       */
      @java.lang.Override
      public boolean hasBufferSize() {
        return ((bitField0_ & 0x00020000) != 0);
      }
      /**
       * <code>optional int32 buffer_size = 18;</code>
       * @return The bufferSize.
       */
      @java.lang.Override
      public int getBufferSize() {
        return bufferSize_;
      }
      /**
       * <code>optional int32 buffer_size = 18;</code>
       * @param value The bufferSize to set.
       * @return This builder for chaining.
       */
      public Builder setBufferSize(int value) {

        bufferSize_ = value;
        bitField0_ |= 0x00020000;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 buffer_size = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearBufferSize() {
        bitField0_ = (bitField0_ & ~0x00020000);
        bufferSize_ = 0;
        onChanged();
        return this;
      }

      private int maxBufferSize_ ;
      /**
       * <code>optional int32 max_buffer_size = 19;</code>
       * @return Whether the maxBufferSize field is set.
       */
      @java.lang.Override
      public boolean hasMaxBufferSize() {
        return ((bitField0_ & 0x00040000) != 0);
      }
      /**
       * <code>optional int32 max_buffer_size = 19;</code>
       * @return The maxBufferSize.
       */
      @java.lang.Override
      public int getMaxBufferSize() {
        return maxBufferSize_;
      }
      /**
       * <code>optional int32 max_buffer_size = 19;</code>
       * @param value The maxBufferSize to set.
       * @return This builder for chaining.
       */
      public Builder setMaxBufferSize(int value) {

        maxBufferSize_ = value;
        bitField0_ |= 0x00040000;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 max_buffer_size = 19;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxBufferSize() {
        bitField0_ = (bitField0_ & ~0x00040000);
        maxBufferSize_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClientStatistics)
    }

    // @@protoc_insertion_point(class_scope:ClientStatistics)
    private static final XTableClientStatistics.ClientStatistics DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new XTableClientStatistics.ClientStatistics();
    }

    public static XTableClientStatistics.ClientStatistics getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientStatistics>
        PARSER = new com.google.protobuf.AbstractParser<ClientStatistics>() {
      @java.lang.Override
      public ClientStatistics parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ClientStatistics> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientStatistics> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public XTableClientStatistics.ClientStatistics getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientStatistics_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClientStatistics_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034XTableClientStatistics.proto\"\212\004\n\020Clien" +
      "tStatistics\022\021\n\tnano_time\030\001 \001(\003\022\025\n\rmax_me" +
      "mory_mb\030\002 \001(\003\022\026\n\016free_memory_mb\030\003 \001(\003\022\026\n" +
      "\016used_memory_mb\030\004 \001(\003\022#\n\033process_cpu_loa" +
      "d_percentage\030\005 \001(\001\022\034\n\024available_processo" +
      "rs\030\006 \001(\005\022\025\n\rtotal_threads\030\007 \001(\003\022\n\n\002ip\030\010 " +
      "\001(\t\022\020\n\010hostname\030\t \001(\t\022\022\n\nprocess_id\030\n \001(" +
      "\t\022\024\n\014lang_version\030\013 \001(\t\022\023\n\013lang_vendor\030\014" +
      " \001(\t\022\020\n\010jvm_name\030\r \001(\t\022\035\n\006health\030\016 \001(\0162\r" +
      ".HealthStatus\022\024\n\007version\030\017 \001(\tH\000\210\001\001\022\021\n\004t" +
      "ype\030\020 \001(\tH\001\210\001\001\022\021\n\004uuid\030\021 \001(\tH\002\210\001\001\022\030\n\013buf" +
      "fer_size\030\022 \001(\005H\003\210\001\001\022\034\n\017max_buffer_size\030\023" +
      " \001(\005H\004\210\001\001B\n\n\010_versionB\007\n\005_typeB\007\n\005_uuidB" +
      "\016\n\014_buffer_sizeB\022\n\020_max_buffer_size*Y\n\014H" +
      "ealthStatus\022\010\n\004GOOD\020\000\022\010\n\004OKAY\020\001\022\014\n\010STRES" +
      "SED\020\002\022\014\n\010OVERLOAD\020\003\022\014\n\010CRITICAL\020\004\022\013\n\007UNK" +
      "NOWN\020\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ClientStatistics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ClientStatistics_descriptor,
        new java.lang.String[] { "NanoTime", "MaxMemoryMb", "FreeMemoryMb", "UsedMemoryMb", "ProcessCpuLoadPercentage", "AvailableProcessors", "TotalThreads", "Ip", "Hostname", "ProcessId", "LangVersion", "LangVendor", "JvmName", "Health", "Version", "Type", "Uuid", "BufferSize", "MaxBufferSize", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
