// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: XTableArrayList.proto
// Protobuf Java Version: 4.29.2

package org.kobe.xbot.Utilities.Entities;

public final class XTableArrayList {
  private XTableArrayList() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      XTableArrayList.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.kobe.xbot.Utilities.Entities.Array)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
     */
    java.util.List<org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value> 
        getValuesList();
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
     */
    org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value getValues(int index);
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
     */
    java.util.List<? extends org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.ValueOrBuilder> 
        getValuesOrBuilderList();
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
     */
    org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.ValueOrBuilder getValuesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.kobe.xbot.Utilities.Entities.Array}
   */
  public static final class Array extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.kobe.xbot.Utilities.Entities.Array)
      ArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        Array.class.getName());
    }
    // Use Array.newBuilder() to construct.
    private Array(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Array() {
      values_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kobe.xbot.Utilities.Entities.XTableArrayList.internal_static_org_kobe_xbot_Utilities_Entities_Array_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kobe.xbot.Utilities.Entities.XTableArrayList.internal_static_org_kobe_xbot_Utilities_Entities_Array_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.class, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Builder.class);
    }

    public interface ValueOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.kobe.xbot.Utilities.Entities.Array.Value)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string string_value = 1;</code>
       * @return Whether the stringValue field is set.
       */
      boolean hasStringValue();
      /**
       * <code>string string_value = 1;</code>
       * @return The stringValue.
       */
      java.lang.String getStringValue();
      /**
       * <code>string string_value = 1;</code>
       * @return The bytes for stringValue.
       */
      com.google.protobuf.ByteString
          getStringValueBytes();

      /**
       * <code>int32 int_value = 2;</code>
       * @return Whether the intValue field is set.
       */
      boolean hasIntValue();
      /**
       * <code>int32 int_value = 2;</code>
       * @return The intValue.
       */
      int getIntValue();

      /**
       * <code>float float_value = 3;</code>
       * @return Whether the floatValue field is set.
       */
      boolean hasFloatValue();
      /**
       * <code>float float_value = 3;</code>
       * @return The floatValue.
       */
      float getFloatValue();

      /**
       * <code>double double_value = 4;</code>
       * @return Whether the doubleValue field is set.
       */
      boolean hasDoubleValue();
      /**
       * <code>double double_value = 4;</code>
       * @return The doubleValue.
       */
      double getDoubleValue();

      /**
       * <code>bool bool_value = 5;</code>
       * @return Whether the boolValue field is set.
       */
      boolean hasBoolValue();
      /**
       * <code>bool bool_value = 5;</code>
       * @return The boolValue.
       */
      boolean getBoolValue();

      /**
       * <code>int64 int64_value = 6;</code>
       * @return Whether the int64Value field is set.
       */
      boolean hasInt64Value();
      /**
       * <code>int64 int64_value = 6;</code>
       * @return The int64Value.
       */
      long getInt64Value();

      /**
       * <code>uint32 uint32_value = 7;</code>
       * @return Whether the uint32Value field is set.
       */
      boolean hasUint32Value();
      /**
       * <code>uint32 uint32_value = 7;</code>
       * @return The uint32Value.
       */
      int getUint32Value();

      /**
       * <code>uint64 uint64_value = 8;</code>
       * @return Whether the uint64Value field is set.
       */
      boolean hasUint64Value();
      /**
       * <code>uint64 uint64_value = 8;</code>
       * @return The uint64Value.
       */
      long getUint64Value();

      /**
       * <code>bytes bytes_value = 9;</code>
       * @return Whether the bytesValue field is set.
       */
      boolean hasBytesValue();
      /**
       * <code>bytes bytes_value = 9;</code>
       * @return The bytesValue.
       */
      com.google.protobuf.ByteString getBytesValue();

      org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.ValueCase getValueCase();
    }
    /**
     * Protobuf type {@code org.kobe.xbot.Utilities.Entities.Array.Value}
     */
    public static final class Value extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:org.kobe.xbot.Utilities.Entities.Array.Value)
        ValueOrBuilder {
    private static final long serialVersionUID = 0L;
      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 29,
          /* patch= */ 2,
          /* suffix= */ "",
          Value.class.getName());
      }
      // Use Value.newBuilder() to construct.
      private Value(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private Value() {
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kobe.xbot.Utilities.Entities.XTableArrayList.internal_static_org_kobe_xbot_Utilities_Entities_Array_Value_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kobe.xbot.Utilities.Entities.XTableArrayList.internal_static_org_kobe_xbot_Utilities_Entities_Array_Value_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.class, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.Builder.class);
      }

      private int valueCase_ = 0;
      @SuppressWarnings("serial")
      private java.lang.Object value_;
      public enum ValueCase
          implements com.google.protobuf.Internal.EnumLite,
              com.google.protobuf.AbstractMessage.InternalOneOfEnum {
        STRING_VALUE(1),
        INT_VALUE(2),
        FLOAT_VALUE(3),
        DOUBLE_VALUE(4),
        BOOL_VALUE(5),
        INT64_VALUE(6),
        UINT32_VALUE(7),
        UINT64_VALUE(8),
        BYTES_VALUE(9),
        VALUE_NOT_SET(0);
        private final int value;
        private ValueCase(int value) {
          this.value = value;
        }
        /**
         * @param value The number of the enum to look for.
         * @return The enum associated with the given number.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static ValueCase valueOf(int value) {
          return forNumber(value);
        }

        public static ValueCase forNumber(int value) {
          switch (value) {
            case 1: return STRING_VALUE;
            case 2: return INT_VALUE;
            case 3: return FLOAT_VALUE;
            case 4: return DOUBLE_VALUE;
            case 5: return BOOL_VALUE;
            case 6: return INT64_VALUE;
            case 7: return UINT32_VALUE;
            case 8: return UINT64_VALUE;
            case 9: return BYTES_VALUE;
            case 0: return VALUE_NOT_SET;
            default: return null;
          }
        }
        public int getNumber() {
          return this.value;
        }
      };

      public ValueCase
      getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public static final int STRING_VALUE_FIELD_NUMBER = 1;
      /**
       * <code>string string_value = 1;</code>
       * @return Whether the stringValue field is set.
       */
      public boolean hasStringValue() {
        return valueCase_ == 1;
      }
      /**
       * <code>string string_value = 1;</code>
       * @return The stringValue.
       */
      public java.lang.String getStringValue() {
        java.lang.Object ref = "";
        if (valueCase_ == 1) {
          ref = value_;
        }
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueCase_ == 1) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>string string_value = 1;</code>
       * @return The bytes for stringValue.
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = "";
        if (valueCase_ == 1) {
          ref = value_;
        }
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueCase_ == 1) {
            value_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int INT_VALUE_FIELD_NUMBER = 2;
      /**
       * <code>int32 int_value = 2;</code>
       * @return Whether the intValue field is set.
       */
      @java.lang.Override
      public boolean hasIntValue() {
        return valueCase_ == 2;
      }
      /**
       * <code>int32 int_value = 2;</code>
       * @return The intValue.
       */
      @java.lang.Override
      public int getIntValue() {
        if (valueCase_ == 2) {
          return (java.lang.Integer) value_;
        }
        return 0;
      }

      public static final int FLOAT_VALUE_FIELD_NUMBER = 3;
      /**
       * <code>float float_value = 3;</code>
       * @return Whether the floatValue field is set.
       */
      @java.lang.Override
      public boolean hasFloatValue() {
        return valueCase_ == 3;
      }
      /**
       * <code>float float_value = 3;</code>
       * @return The floatValue.
       */
      @java.lang.Override
      public float getFloatValue() {
        if (valueCase_ == 3) {
          return (java.lang.Float) value_;
        }
        return 0F;
      }

      public static final int DOUBLE_VALUE_FIELD_NUMBER = 4;
      /**
       * <code>double double_value = 4;</code>
       * @return Whether the doubleValue field is set.
       */
      @java.lang.Override
      public boolean hasDoubleValue() {
        return valueCase_ == 4;
      }
      /**
       * <code>double double_value = 4;</code>
       * @return The doubleValue.
       */
      @java.lang.Override
      public double getDoubleValue() {
        if (valueCase_ == 4) {
          return (java.lang.Double) value_;
        }
        return 0D;
      }

      public static final int BOOL_VALUE_FIELD_NUMBER = 5;
      /**
       * <code>bool bool_value = 5;</code>
       * @return Whether the boolValue field is set.
       */
      @java.lang.Override
      public boolean hasBoolValue() {
        return valueCase_ == 5;
      }
      /**
       * <code>bool bool_value = 5;</code>
       * @return The boolValue.
       */
      @java.lang.Override
      public boolean getBoolValue() {
        if (valueCase_ == 5) {
          return (java.lang.Boolean) value_;
        }
        return false;
      }

      public static final int INT64_VALUE_FIELD_NUMBER = 6;
      /**
       * <code>int64 int64_value = 6;</code>
       * @return Whether the int64Value field is set.
       */
      @java.lang.Override
      public boolean hasInt64Value() {
        return valueCase_ == 6;
      }
      /**
       * <code>int64 int64_value = 6;</code>
       * @return The int64Value.
       */
      @java.lang.Override
      public long getInt64Value() {
        if (valueCase_ == 6) {
          return (java.lang.Long) value_;
        }
        return 0L;
      }

      public static final int UINT32_VALUE_FIELD_NUMBER = 7;
      /**
       * <code>uint32 uint32_value = 7;</code>
       * @return Whether the uint32Value field is set.
       */
      @java.lang.Override
      public boolean hasUint32Value() {
        return valueCase_ == 7;
      }
      /**
       * <code>uint32 uint32_value = 7;</code>
       * @return The uint32Value.
       */
      @java.lang.Override
      public int getUint32Value() {
        if (valueCase_ == 7) {
          return (java.lang.Integer) value_;
        }
        return 0;
      }

      public static final int UINT64_VALUE_FIELD_NUMBER = 8;
      /**
       * <code>uint64 uint64_value = 8;</code>
       * @return Whether the uint64Value field is set.
       */
      @java.lang.Override
      public boolean hasUint64Value() {
        return valueCase_ == 8;
      }
      /**
       * <code>uint64 uint64_value = 8;</code>
       * @return The uint64Value.
       */
      @java.lang.Override
      public long getUint64Value() {
        if (valueCase_ == 8) {
          return (java.lang.Long) value_;
        }
        return 0L;
      }

      public static final int BYTES_VALUE_FIELD_NUMBER = 9;
      /**
       * <code>bytes bytes_value = 9;</code>
       * @return Whether the bytesValue field is set.
       */
      @java.lang.Override
      public boolean hasBytesValue() {
        return valueCase_ == 9;
      }
      /**
       * <code>bytes bytes_value = 9;</code>
       * @return The bytesValue.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBytesValue() {
        if (valueCase_ == 9) {
          return (com.google.protobuf.ByteString) value_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (valueCase_ == 1) {
          com.google.protobuf.GeneratedMessage.writeString(output, 1, value_);
        }
        if (valueCase_ == 2) {
          output.writeInt32(
              2, (int)((java.lang.Integer) value_));
        }
        if (valueCase_ == 3) {
          output.writeFloat(
              3, (float)((java.lang.Float) value_));
        }
        if (valueCase_ == 4) {
          output.writeDouble(
              4, (double)((java.lang.Double) value_));
        }
        if (valueCase_ == 5) {
          output.writeBool(
              5, (boolean)((java.lang.Boolean) value_));
        }
        if (valueCase_ == 6) {
          output.writeInt64(
              6, (long)((java.lang.Long) value_));
        }
        if (valueCase_ == 7) {
          output.writeUInt32(
              7, (int)((java.lang.Integer) value_));
        }
        if (valueCase_ == 8) {
          output.writeUInt64(
              8, (long)((java.lang.Long) value_));
        }
        if (valueCase_ == 9) {
          output.writeBytes(
              9, (com.google.protobuf.ByteString) value_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (valueCase_ == 1) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(1, value_);
        }
        if (valueCase_ == 2) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(
                2, (int)((java.lang.Integer) value_));
        }
        if (valueCase_ == 3) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(
                3, (float)((java.lang.Float) value_));
        }
        if (valueCase_ == 4) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(
                4, (double)((java.lang.Double) value_));
        }
        if (valueCase_ == 5) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(
                5, (boolean)((java.lang.Boolean) value_));
        }
        if (valueCase_ == 6) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(
                6, (long)((java.lang.Long) value_));
        }
        if (valueCase_ == 7) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(
                7, (int)((java.lang.Integer) value_));
        }
        if (valueCase_ == 8) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(
                8, (long)((java.lang.Long) value_));
        }
        if (valueCase_ == 9) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(
                9, (com.google.protobuf.ByteString) value_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value)) {
          return super.equals(obj);
        }
        org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value other = (org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value) obj;

        if (!getValueCase().equals(other.getValueCase())) return false;
        switch (valueCase_) {
          case 1:
            if (!getStringValue()
                .equals(other.getStringValue())) return false;
            break;
          case 2:
            if (getIntValue()
                != other.getIntValue()) return false;
            break;
          case 3:
            if (java.lang.Float.floatToIntBits(getFloatValue())
                != java.lang.Float.floatToIntBits(
                    other.getFloatValue())) return false;
            break;
          case 4:
            if (java.lang.Double.doubleToLongBits(getDoubleValue())
                != java.lang.Double.doubleToLongBits(
                    other.getDoubleValue())) return false;
            break;
          case 5:
            if (getBoolValue()
                != other.getBoolValue()) return false;
            break;
          case 6:
            if (getInt64Value()
                != other.getInt64Value()) return false;
            break;
          case 7:
            if (getUint32Value()
                != other.getUint32Value()) return false;
            break;
          case 8:
            if (getUint64Value()
                != other.getUint64Value()) return false;
            break;
          case 9:
            if (!getBytesValue()
                .equals(other.getBytesValue())) return false;
            break;
          case 0:
          default:
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        switch (valueCase_) {
          case 1:
            hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
            hash = (53 * hash) + getStringValue().hashCode();
            break;
          case 2:
            hash = (37 * hash) + INT_VALUE_FIELD_NUMBER;
            hash = (53 * hash) + getIntValue();
            break;
          case 3:
            hash = (37 * hash) + FLOAT_VALUE_FIELD_NUMBER;
            hash = (53 * hash) + java.lang.Float.floatToIntBits(
                getFloatValue());
            break;
          case 4:
            hash = (37 * hash) + DOUBLE_VALUE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                java.lang.Double.doubleToLongBits(getDoubleValue()));
            break;
          case 5:
            hash = (37 * hash) + BOOL_VALUE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getBoolValue());
            break;
          case 6:
            hash = (37 * hash) + INT64_VALUE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getInt64Value());
            break;
          case 7:
            hash = (37 * hash) + UINT32_VALUE_FIELD_NUMBER;
            hash = (53 * hash) + getUint32Value();
            break;
          case 8:
            hash = (37 * hash) + UINT64_VALUE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getUint64Value());
            break;
          case 9:
            hash = (37 * hash) + BYTES_VALUE_FIELD_NUMBER;
            hash = (53 * hash) + getBytesValue().hashCode();
            break;
          case 0:
          default:
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code org.kobe.xbot.Utilities.Entities.Array.Value}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:org.kobe.xbot.Utilities.Entities.Array.Value)
          org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.ValueOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.kobe.xbot.Utilities.Entities.XTableArrayList.internal_static_org_kobe_xbot_Utilities_Entities_Array_Value_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.kobe.xbot.Utilities.Entities.XTableArrayList.internal_static_org_kobe_xbot_Utilities_Entities_Array_Value_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.class, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.Builder.class);
        }

        // Construct using org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          valueCase_ = 0;
          value_ = null;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.kobe.xbot.Utilities.Entities.XTableArrayList.internal_static_org_kobe_xbot_Utilities_Entities_Array_Value_descriptor;
        }

        @java.lang.Override
        public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value getDefaultInstanceForType() {
          return org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.getDefaultInstance();
        }

        @java.lang.Override
        public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value build() {
          org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value buildPartial() {
          org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value result = new org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          buildPartialOneofs(result);
          onBuilt();
          return result;
        }

        private void buildPartial0(org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value result) {
          int from_bitField0_ = bitField0_;
        }

        private void buildPartialOneofs(org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value result) {
          result.valueCase_ = valueCase_;
          result.value_ = this.value_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value) {
            return mergeFrom((org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value other) {
          if (other == org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.getDefaultInstance()) return this;
          switch (other.getValueCase()) {
            case STRING_VALUE: {
              valueCase_ = 1;
              value_ = other.value_;
              onChanged();
              break;
            }
            case INT_VALUE: {
              setIntValue(other.getIntValue());
              break;
            }
            case FLOAT_VALUE: {
              setFloatValue(other.getFloatValue());
              break;
            }
            case DOUBLE_VALUE: {
              setDoubleValue(other.getDoubleValue());
              break;
            }
            case BOOL_VALUE: {
              setBoolValue(other.getBoolValue());
              break;
            }
            case INT64_VALUE: {
              setInt64Value(other.getInt64Value());
              break;
            }
            case UINT32_VALUE: {
              setUint32Value(other.getUint32Value());
              break;
            }
            case UINT64_VALUE: {
              setUint64Value(other.getUint64Value());
              break;
            }
            case BYTES_VALUE: {
              setBytesValue(other.getBytesValue());
              break;
            }
            case VALUE_NOT_SET: {
              break;
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  java.lang.String s = input.readStringRequireUtf8();
                  valueCase_ = 1;
                  value_ = s;
                  break;
                } // case 10
                case 16: {
                  value_ = input.readInt32();
                  valueCase_ = 2;
                  break;
                } // case 16
                case 29: {
                  value_ = input.readFloat();
                  valueCase_ = 3;
                  break;
                } // case 29
                case 33: {
                  value_ = input.readDouble();
                  valueCase_ = 4;
                  break;
                } // case 33
                case 40: {
                  value_ = input.readBool();
                  valueCase_ = 5;
                  break;
                } // case 40
                case 48: {
                  value_ = input.readInt64();
                  valueCase_ = 6;
                  break;
                } // case 48
                case 56: {
                  value_ = input.readUInt32();
                  valueCase_ = 7;
                  break;
                } // case 56
                case 64: {
                  value_ = input.readUInt64();
                  valueCase_ = 8;
                  break;
                } // case 64
                case 74: {
                  value_ = input.readBytes();
                  valueCase_ = 9;
                  break;
                } // case 74
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int valueCase_ = 0;
        private java.lang.Object value_;
        public ValueCase
            getValueCase() {
          return ValueCase.forNumber(
              valueCase_);
        }

        public Builder clearValue() {
          valueCase_ = 0;
          value_ = null;
          onChanged();
          return this;
        }

        private int bitField0_;

        /**
         * <code>string string_value = 1;</code>
         * @return Whether the stringValue field is set.
         */
        @java.lang.Override
        public boolean hasStringValue() {
          return valueCase_ == 1;
        }
        /**
         * <code>string string_value = 1;</code>
         * @return The stringValue.
         */
        @java.lang.Override
        public java.lang.String getStringValue() {
          java.lang.Object ref = "";
          if (valueCase_ == 1) {
            ref = value_;
          }
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (valueCase_ == 1) {
              value_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string string_value = 1;</code>
         * @return The bytes for stringValue.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
            getStringValueBytes() {
          java.lang.Object ref = "";
          if (valueCase_ == 1) {
            ref = value_;
          }
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            if (valueCase_ == 1) {
              value_ = b;
            }
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string string_value = 1;</code>
         * @param value The stringValue to set.
         * @return This builder for chaining.
         */
        public Builder setStringValue(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          valueCase_ = 1;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string string_value = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearStringValue() {
          if (valueCase_ == 1) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }
        /**
         * <code>string string_value = 1;</code>
         * @param value The bytes for stringValue to set.
         * @return This builder for chaining.
         */
        public Builder setStringValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          valueCase_ = 1;
          value_ = value;
          onChanged();
          return this;
        }

        /**
         * <code>int32 int_value = 2;</code>
         * @return Whether the intValue field is set.
         */
        public boolean hasIntValue() {
          return valueCase_ == 2;
        }
        /**
         * <code>int32 int_value = 2;</code>
         * @return The intValue.
         */
        public int getIntValue() {
          if (valueCase_ == 2) {
            return (java.lang.Integer) value_;
          }
          return 0;
        }
        /**
         * <code>int32 int_value = 2;</code>
         * @param value The intValue to set.
         * @return This builder for chaining.
         */
        public Builder setIntValue(int value) {

          valueCase_ = 2;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 int_value = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearIntValue() {
          if (valueCase_ == 2) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>float float_value = 3;</code>
         * @return Whether the floatValue field is set.
         */
        public boolean hasFloatValue() {
          return valueCase_ == 3;
        }
        /**
         * <code>float float_value = 3;</code>
         * @return The floatValue.
         */
        public float getFloatValue() {
          if (valueCase_ == 3) {
            return (java.lang.Float) value_;
          }
          return 0F;
        }
        /**
         * <code>float float_value = 3;</code>
         * @param value The floatValue to set.
         * @return This builder for chaining.
         */
        public Builder setFloatValue(float value) {

          valueCase_ = 3;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float float_value = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearFloatValue() {
          if (valueCase_ == 3) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>double double_value = 4;</code>
         * @return Whether the doubleValue field is set.
         */
        public boolean hasDoubleValue() {
          return valueCase_ == 4;
        }
        /**
         * <code>double double_value = 4;</code>
         * @return The doubleValue.
         */
        public double getDoubleValue() {
          if (valueCase_ == 4) {
            return (java.lang.Double) value_;
          }
          return 0D;
        }
        /**
         * <code>double double_value = 4;</code>
         * @param value The doubleValue to set.
         * @return This builder for chaining.
         */
        public Builder setDoubleValue(double value) {

          valueCase_ = 4;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double double_value = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearDoubleValue() {
          if (valueCase_ == 4) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>bool bool_value = 5;</code>
         * @return Whether the boolValue field is set.
         */
        public boolean hasBoolValue() {
          return valueCase_ == 5;
        }
        /**
         * <code>bool bool_value = 5;</code>
         * @return The boolValue.
         */
        public boolean getBoolValue() {
          if (valueCase_ == 5) {
            return (java.lang.Boolean) value_;
          }
          return false;
        }
        /**
         * <code>bool bool_value = 5;</code>
         * @param value The boolValue to set.
         * @return This builder for chaining.
         */
        public Builder setBoolValue(boolean value) {

          valueCase_ = 5;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bool bool_value = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearBoolValue() {
          if (valueCase_ == 5) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>int64 int64_value = 6;</code>
         * @return Whether the int64Value field is set.
         */
        public boolean hasInt64Value() {
          return valueCase_ == 6;
        }
        /**
         * <code>int64 int64_value = 6;</code>
         * @return The int64Value.
         */
        public long getInt64Value() {
          if (valueCase_ == 6) {
            return (java.lang.Long) value_;
          }
          return 0L;
        }
        /**
         * <code>int64 int64_value = 6;</code>
         * @param value The int64Value to set.
         * @return This builder for chaining.
         */
        public Builder setInt64Value(long value) {

          valueCase_ = 6;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 int64_value = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearInt64Value() {
          if (valueCase_ == 6) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>uint32 uint32_value = 7;</code>
         * @return Whether the uint32Value field is set.
         */
        public boolean hasUint32Value() {
          return valueCase_ == 7;
        }
        /**
         * <code>uint32 uint32_value = 7;</code>
         * @return The uint32Value.
         */
        public int getUint32Value() {
          if (valueCase_ == 7) {
            return (java.lang.Integer) value_;
          }
          return 0;
        }
        /**
         * <code>uint32 uint32_value = 7;</code>
         * @param value The uint32Value to set.
         * @return This builder for chaining.
         */
        public Builder setUint32Value(int value) {

          valueCase_ = 7;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 uint32_value = 7;</code>
         * @return This builder for chaining.
         */
        public Builder clearUint32Value() {
          if (valueCase_ == 7) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>uint64 uint64_value = 8;</code>
         * @return Whether the uint64Value field is set.
         */
        public boolean hasUint64Value() {
          return valueCase_ == 8;
        }
        /**
         * <code>uint64 uint64_value = 8;</code>
         * @return The uint64Value.
         */
        public long getUint64Value() {
          if (valueCase_ == 8) {
            return (java.lang.Long) value_;
          }
          return 0L;
        }
        /**
         * <code>uint64 uint64_value = 8;</code>
         * @param value The uint64Value to set.
         * @return This builder for chaining.
         */
        public Builder setUint64Value(long value) {

          valueCase_ = 8;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint64 uint64_value = 8;</code>
         * @return This builder for chaining.
         */
        public Builder clearUint64Value() {
          if (valueCase_ == 8) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>bytes bytes_value = 9;</code>
         * @return Whether the bytesValue field is set.
         */
        public boolean hasBytesValue() {
          return valueCase_ == 9;
        }
        /**
         * <code>bytes bytes_value = 9;</code>
         * @return The bytesValue.
         */
        public com.google.protobuf.ByteString getBytesValue() {
          if (valueCase_ == 9) {
            return (com.google.protobuf.ByteString) value_;
          }
          return com.google.protobuf.ByteString.EMPTY;
        }
        /**
         * <code>bytes bytes_value = 9;</code>
         * @param value The bytesValue to set.
         * @return This builder for chaining.
         */
        public Builder setBytesValue(com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          valueCase_ = 9;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes bytes_value = 9;</code>
         * @return This builder for chaining.
         */
        public Builder clearBytesValue() {
          if (valueCase_ == 9) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        // @@protoc_insertion_point(builder_scope:org.kobe.xbot.Utilities.Entities.Array.Value)
      }

      // @@protoc_insertion_point(class_scope:org.kobe.xbot.Utilities.Entities.Array.Value)
      private static final org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value();
      }

      public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Value>
          PARSER = new com.google.protobuf.AbstractParser<Value>() {
        @java.lang.Override
        public Value parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Value> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Value> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int VALUES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value> values_;
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value> getValuesList() {
      return values_;
    }
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.ValueOrBuilder> 
        getValuesOrBuilderList() {
      return values_;
    }
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
     */
    @java.lang.Override
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
     */
    @java.lang.Override
    public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
     */
    @java.lang.Override
    public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.ValueOrBuilder getValuesOrBuilder(
        int index) {
      return values_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < values_.size(); i++) {
        output.writeMessage(1, values_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < values_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, values_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.kobe.xbot.Utilities.Entities.XTableArrayList.Array)) {
        return super.equals(obj);
      }
      org.kobe.xbot.Utilities.Entities.XTableArrayList.Array other = (org.kobe.xbot.Utilities.Entities.XTableArrayList.Array) obj;

      if (!getValuesList()
          .equals(other.getValuesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValuesCount() > 0) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getValuesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.kobe.xbot.Utilities.Entities.XTableArrayList.Array prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.kobe.xbot.Utilities.Entities.Array}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.kobe.xbot.Utilities.Entities.Array)
        org.kobe.xbot.Utilities.Entities.XTableArrayList.ArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kobe.xbot.Utilities.Entities.XTableArrayList.internal_static_org_kobe_xbot_Utilities_Entities_Array_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kobe.xbot.Utilities.Entities.XTableArrayList.internal_static_org_kobe_xbot_Utilities_Entities_Array_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.class, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Builder.class);
      }

      // Construct using org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
        } else {
          values_ = null;
          valuesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kobe.xbot.Utilities.Entities.XTableArrayList.internal_static_org_kobe_xbot_Utilities_Entities_Array_descriptor;
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array getDefaultInstanceForType() {
        return org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.getDefaultInstance();
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array build() {
        org.kobe.xbot.Utilities.Entities.XTableArrayList.Array result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array buildPartial() {
        org.kobe.xbot.Utilities.Entities.XTableArrayList.Array result = new org.kobe.xbot.Utilities.Entities.XTableArrayList.Array(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.kobe.xbot.Utilities.Entities.XTableArrayList.Array result) {
        if (valuesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            values_ = java.util.Collections.unmodifiableList(values_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.values_ = values_;
        } else {
          result.values_ = valuesBuilder_.build();
        }
      }

      private void buildPartial0(org.kobe.xbot.Utilities.Entities.XTableArrayList.Array result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kobe.xbot.Utilities.Entities.XTableArrayList.Array) {
          return mergeFrom((org.kobe.xbot.Utilities.Entities.XTableArrayList.Array)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.kobe.xbot.Utilities.Entities.XTableArrayList.Array other) {
        if (other == org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.getDefaultInstance()) return this;
        if (valuesBuilder_ == null) {
          if (!other.values_.isEmpty()) {
            if (values_.isEmpty()) {
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValuesIsMutable();
              values_.addAll(other.values_);
            }
            onChanged();
          }
        } else {
          if (!other.values_.isEmpty()) {
            if (valuesBuilder_.isEmpty()) {
              valuesBuilder_.dispose();
              valuesBuilder_ = null;
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000001);
              valuesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getValuesFieldBuilder() : null;
            } else {
              valuesBuilder_.addAllMessages(other.values_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value m =
                    input.readMessage(
                        org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.parser(),
                        extensionRegistry);
                if (valuesBuilder_ == null) {
                  ensureValuesIsMutable();
                  values_.add(m);
                } else {
                  valuesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value> values_ =
        java.util.Collections.emptyList();
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          values_ = new java.util.ArrayList<org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value>(values_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.Builder, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.ValueOrBuilder> valuesBuilder_;

      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public java.util.List<org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value> getValuesList() {
        if (valuesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(values_);
        } else {
          return valuesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public int getValuesCount() {
        if (valuesBuilder_ == null) {
          return values_.size();
        } else {
          return valuesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value getValues(int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);
        } else {
          return valuesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public Builder setValues(
          int index, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.set(index, value);
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public Builder setValues(
          int index, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.set(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public Builder addValues(org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public Builder addValues(
          int index, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(index, value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public Builder addValues(
          org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public Builder addValues(
          int index, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value> values) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, values_);
          onChanged();
        } else {
          valuesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public Builder clearValues() {
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          valuesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public Builder removeValues(int index) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.remove(index);
          onChanged();
        } else {
          valuesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.Builder getValuesBuilder(
          int index) {
        return getValuesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.ValueOrBuilder getValuesOrBuilder(
          int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);  } else {
          return valuesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public java.util.List<? extends org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.ValueOrBuilder> 
           getValuesOrBuilderList() {
        if (valuesBuilder_ != null) {
          return valuesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(values_);
        }
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.Builder addValuesBuilder() {
        return getValuesFieldBuilder().addBuilder(
            org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.getDefaultInstance());
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.Builder addValuesBuilder(
          int index) {
        return getValuesFieldBuilder().addBuilder(
            index, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.getDefaultInstance());
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Array.Value values = 1;</code>
       */
      public java.util.List<org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.Builder> 
           getValuesBuilderList() {
        return getValuesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.Builder, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.ValueOrBuilder> 
          getValuesFieldBuilder() {
        if (valuesBuilder_ == null) {
          valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.Value.Builder, org.kobe.xbot.Utilities.Entities.XTableArrayList.Array.ValueOrBuilder>(
                  values_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          values_ = null;
        }
        return valuesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.kobe.xbot.Utilities.Entities.Array)
    }

    // @@protoc_insertion_point(class_scope:org.kobe.xbot.Utilities.Entities.Array)
    private static final org.kobe.xbot.Utilities.Entities.XTableArrayList.Array DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.kobe.xbot.Utilities.Entities.XTableArrayList.Array();
    }

    public static org.kobe.xbot.Utilities.Entities.XTableArrayList.Array getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Array>
        PARSER = new com.google.protobuf.AbstractParser<Array>() {
      @java.lang.Override
      public Array parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Array> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Array> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.kobe.xbot.Utilities.Entities.XTableArrayList.Array getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_kobe_xbot_Utilities_Entities_Array_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_kobe_xbot_Utilities_Entities_Array_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_kobe_xbot_Utilities_Entities_Array_Value_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_kobe_xbot_Utilities_Entities_Array_Value_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025XTableArrayList.proto\022 org.kobe.xbot.U" +
      "tilities.Entities\"\251\002\n\005Array\022=\n\006values\030\001 " +
      "\003(\0132-.org.kobe.xbot.Utilities.Entities.A" +
      "rray.Value\032\340\001\n\005Value\022\026\n\014string_value\030\001 \001" +
      "(\tH\000\022\023\n\tint_value\030\002 \001(\005H\000\022\025\n\013float_value" +
      "\030\003 \001(\002H\000\022\026\n\014double_value\030\004 \001(\001H\000\022\024\n\nbool" +
      "_value\030\005 \001(\010H\000\022\025\n\013int64_value\030\006 \001(\003H\000\022\026\n" +
      "\014uint32_value\030\007 \001(\rH\000\022\026\n\014uint64_value\030\010 " +
      "\001(\004H\000\022\025\n\013bytes_value\030\t \001(\014H\000B\007\n\005valueb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_kobe_xbot_Utilities_Entities_Array_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_kobe_xbot_Utilities_Entities_Array_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_kobe_xbot_Utilities_Entities_Array_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_org_kobe_xbot_Utilities_Entities_Array_Value_descriptor =
      internal_static_org_kobe_xbot_Utilities_Entities_Array_descriptor.getNestedTypes().get(0);
    internal_static_org_kobe_xbot_Utilities_Entities_Array_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_kobe_xbot_Utilities_Entities_Array_Value_descriptor,
        new java.lang.String[] { "StringValue", "IntValue", "FloatValue", "DoubleValue", "BoolValue", "Int64Value", "Uint32Value", "Uint64Value", "BytesValue", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
