package org.kobe.xbot.Utilities.Entities;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: XTableProto.proto
// Protobuf Java Version: 4.29.2

public final class XTableProto {
  private XTableProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      XTableProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface XTableMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:XTableMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>optional .XTableMessage.Command command = 2;</code>
     * @return Whether the command field is set.
     */
    boolean hasCommand();
    /**
     * <code>optional .XTableMessage.Command command = 2;</code>
     * @return The enum numeric value on the wire for command.
     */
    int getCommandValue();
    /**
     * <code>optional .XTableMessage.Command command = 2;</code>
     * @return The command.
     */
    XTableProto.XTableMessage.Command getCommand();

    /**
     * <code>optional string key = 3;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <code>optional string key = 3;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 3;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional bytes value = 4;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>optional bytes value = 4;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>optional .XTableMessage.Type type = 5;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional .XTableMessage.Type type = 5;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>optional .XTableMessage.Type type = 5;</code>
     * @return The type.
     */
    XTableProto.XTableMessage.Type getType();
  }
  /**
   * Protobuf type {@code XTableMessage}
   */
  public static final class XTableMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:XTableMessage)
      XTableMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        XTableMessage.class.getName());
    }
    // Use XTableMessage.newBuilder() to construct.
    private XTableMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private XTableMessage() {
      command_ = 0;
      key_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
      type_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return XTableProto.internal_static_XTableMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return XTableProto.internal_static_XTableMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              XTableProto.XTableMessage.class, XTableProto.XTableMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code XTableMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>STRING = 1;</code>
       */
      STRING(1),
      /**
       * <code>DOUBLE = 2;</code>
       */
      DOUBLE(2),
      /**
       * <code>INT64 = 5;</code>
       */
      INT64(5),
      /**
       * <code>BOOL = 6;</code>
       */
      BOOL(6),
      /**
       * <code>BYTES = 7;</code>
       */
      BYTES(7),
      /**
       * <code>ENUM = 8;</code>
       */
      ENUM(8),
      /**
       * <code>MESSAGE = 9;</code>
       */
      MESSAGE(9),
      /**
       * <code>ARRAY = 10;</code>
       */
      ARRAY(10),
      /**
       * <code>OBJECT = 11;</code>
       */
      OBJECT(11),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 29,
          /* patch= */ 2,
          /* suffix= */ "",
          Type.class.getName());
      }
      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>STRING = 1;</code>
       */
      public static final int STRING_VALUE = 1;
      /**
       * <code>DOUBLE = 2;</code>
       */
      public static final int DOUBLE_VALUE = 2;
      /**
       * <code>INT64 = 5;</code>
       */
      public static final int INT64_VALUE = 5;
      /**
       * <code>BOOL = 6;</code>
       */
      public static final int BOOL_VALUE = 6;
      /**
       * <code>BYTES = 7;</code>
       */
      public static final int BYTES_VALUE = 7;
      /**
       * <code>ENUM = 8;</code>
       */
      public static final int ENUM_VALUE = 8;
      /**
       * <code>MESSAGE = 9;</code>
       */
      public static final int MESSAGE_VALUE = 9;
      /**
       * <code>ARRAY = 10;</code>
       */
      public static final int ARRAY_VALUE = 10;
      /**
       * <code>OBJECT = 11;</code>
       */
      public static final int OBJECT_VALUE = 11;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return STRING;
          case 2: return DOUBLE;
          case 5: return INT64;
          case 6: return BOOL;
          case 7: return BYTES;
          case 8: return ENUM;
          case 9: return MESSAGE;
          case 10: return ARRAY;
          case 11: return OBJECT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return XTableProto.XTableMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:XTableMessage.Type)
    }

    /**
     * Protobuf enum {@code XTableMessage.Command}
     */
    public enum Command
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN_COMMAND = 0;</code>
       */
      UNKNOWN_COMMAND(0),
      /**
       * <code>PUT = 1;</code>
       */
      PUT(1),
      /**
       * <code>GET = 2;</code>
       */
      GET(2),
      /**
       * <code>SUBSCRIBE_UPDATE = 3;</code>
       */
      SUBSCRIBE_UPDATE(3),
      /**
       * <code>GET_TABLES = 4;</code>
       */
      GET_TABLES(4),
      /**
       * <code>RUN_SCRIPT = 5;</code>
       */
      RUN_SCRIPT(5),
      /**
       * <code>UPDATE_KEY = 6;</code>
       */
      UPDATE_KEY(6),
      /**
       * <code>DELETE = 7;</code>
       */
      DELETE(7),
      /**
       * <code>PUBLISH = 8;</code>
       */
      PUBLISH(8),
      /**
       * <code>SUBSCRIBE_DELETE = 9;</code>
       */
      SUBSCRIBE_DELETE(9),
      /**
       * <code>UNSUBSCRIBE_DELETE = 10;</code>
       */
      UNSUBSCRIBE_DELETE(10),
      /**
       * <code>UNSUBSCRIBE_UPDATE = 11;</code>
       */
      UNSUBSCRIBE_UPDATE(11),
      /**
       * <code>PING = 12;</code>
       */
      PING(12),
      /**
       * <code>GET_RAW_JSON = 13;</code>
       */
      GET_RAW_JSON(13),
      /**
       * <code>DELETE_EVENT = 14;</code>
       */
      DELETE_EVENT(14),
      /**
       * <code>UPDATE_EVENT = 15;</code>
       */
      UPDATE_EVENT(15),
      /**
       * <code>INFORMATION = 16;</code>
       */
      INFORMATION(16),
      /**
       * <code>REBOOT_SERVER = 17;</code>
       */
      REBOOT_SERVER(17),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 29,
          /* patch= */ 2,
          /* suffix= */ "",
          Command.class.getName());
      }
      /**
       * <code>UNKNOWN_COMMAND = 0;</code>
       */
      public static final int UNKNOWN_COMMAND_VALUE = 0;
      /**
       * <code>PUT = 1;</code>
       */
      public static final int PUT_VALUE = 1;
      /**
       * <code>GET = 2;</code>
       */
      public static final int GET_VALUE = 2;
      /**
       * <code>SUBSCRIBE_UPDATE = 3;</code>
       */
      public static final int SUBSCRIBE_UPDATE_VALUE = 3;
      /**
       * <code>GET_TABLES = 4;</code>
       */
      public static final int GET_TABLES_VALUE = 4;
      /**
       * <code>RUN_SCRIPT = 5;</code>
       */
      public static final int RUN_SCRIPT_VALUE = 5;
      /**
       * <code>UPDATE_KEY = 6;</code>
       */
      public static final int UPDATE_KEY_VALUE = 6;
      /**
       * <code>DELETE = 7;</code>
       */
      public static final int DELETE_VALUE = 7;
      /**
       * <code>PUBLISH = 8;</code>
       */
      public static final int PUBLISH_VALUE = 8;
      /**
       * <code>SUBSCRIBE_DELETE = 9;</code>
       */
      public static final int SUBSCRIBE_DELETE_VALUE = 9;
      /**
       * <code>UNSUBSCRIBE_DELETE = 10;</code>
       */
      public static final int UNSUBSCRIBE_DELETE_VALUE = 10;
      /**
       * <code>UNSUBSCRIBE_UPDATE = 11;</code>
       */
      public static final int UNSUBSCRIBE_UPDATE_VALUE = 11;
      /**
       * <code>PING = 12;</code>
       */
      public static final int PING_VALUE = 12;
      /**
       * <code>GET_RAW_JSON = 13;</code>
       */
      public static final int GET_RAW_JSON_VALUE = 13;
      /**
       * <code>DELETE_EVENT = 14;</code>
       */
      public static final int DELETE_EVENT_VALUE = 14;
      /**
       * <code>UPDATE_EVENT = 15;</code>
       */
      public static final int UPDATE_EVENT_VALUE = 15;
      /**
       * <code>INFORMATION = 16;</code>
       */
      public static final int INFORMATION_VALUE = 16;
      /**
       * <code>REBOOT_SERVER = 17;</code>
       */
      public static final int REBOOT_SERVER_VALUE = 17;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Command valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Command forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_COMMAND;
          case 1: return PUT;
          case 2: return GET;
          case 3: return SUBSCRIBE_UPDATE;
          case 4: return GET_TABLES;
          case 5: return RUN_SCRIPT;
          case 6: return UPDATE_KEY;
          case 7: return DELETE;
          case 8: return PUBLISH;
          case 9: return SUBSCRIBE_DELETE;
          case 10: return UNSUBSCRIBE_DELETE;
          case 11: return UNSUBSCRIBE_UPDATE;
          case 12: return PING;
          case 13: return GET_RAW_JSON;
          case 14: return DELETE_EVENT;
          case 15: return UPDATE_EVENT;
          case 16: return INFORMATION;
          case 17: return REBOOT_SERVER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Command> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Command>() {
              public Command findValueByNumber(int number) {
                return Command.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return XTableProto.XTableMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final Command[] VALUES = values();

      public static Command valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Command(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:XTableMessage.Command)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>optional int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int COMMAND_FIELD_NUMBER = 2;
    private int command_ = 0;
    /**
     * <code>optional .XTableMessage.Command command = 2;</code>
     * @return Whether the command field is set.
     */
    @java.lang.Override public boolean hasCommand() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .XTableMessage.Command command = 2;</code>
     * @return The enum numeric value on the wire for command.
     */
    @java.lang.Override public int getCommandValue() {
      return command_;
    }
    /**
     * <code>optional .XTableMessage.Command command = 2;</code>
     * @return The command.
     */
    @java.lang.Override public XTableProto.XTableMessage.Command getCommand() {
      XTableProto.XTableMessage.Command result = XTableProto.XTableMessage.Command.forNumber(command_);
      return result == null ? XTableProto.XTableMessage.Command.UNRECOGNIZED : result;
    }

    public static final int KEY_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object key_ = "";
    /**
     * <code>optional string key = 3;</code>
     * @return Whether the key field is set.
     */
    @java.lang.Override
    public boolean hasKey() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string key = 3;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>optional string key = 3;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes value = 4;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes value = 4;</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_ = 0;
    /**
     * <code>optional .XTableMessage.Type type = 5;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .XTableMessage.Type type = 5;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .XTableMessage.Type type = 5;</code>
     * @return The type.
     */
    @java.lang.Override public XTableProto.XTableMessage.Type getType() {
      XTableProto.XTableMessage.Type result = XTableProto.XTableMessage.Type.forNumber(type_);
      return result == null ? XTableProto.XTableMessage.Type.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, command_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, key_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, value_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeEnum(5, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, command_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, key_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, value_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof XTableProto.XTableMessage)) {
        return super.equals(obj);
      }
      XTableProto.XTableMessage other = (XTableProto.XTableMessage) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasCommand() != other.hasCommand()) return false;
      if (hasCommand()) {
        if (command_ != other.command_) return false;
      }
      if (hasKey() != other.hasKey()) return false;
      if (hasKey()) {
        if (!getKey()
            .equals(other.getKey())) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasCommand()) {
        hash = (37 * hash) + COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + command_;
      }
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static XTableProto.XTableMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static XTableProto.XTableMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static XTableProto.XTableMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static XTableProto.XTableMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static XTableProto.XTableMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static XTableProto.XTableMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static XTableProto.XTableMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static XTableProto.XTableMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static XTableProto.XTableMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static XTableProto.XTableMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static XTableProto.XTableMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static XTableProto.XTableMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(XTableProto.XTableMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code XTableMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:XTableMessage)
        XTableProto.XTableMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return XTableProto.internal_static_XTableMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return XTableProto.internal_static_XTableMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                XTableProto.XTableMessage.class, XTableProto.XTableMessage.Builder.class);
      }

      // Construct using XTableProto.XTableMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        command_ = 0;
        key_ = "";
        value_ = com.google.protobuf.ByteString.EMPTY;
        type_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return XTableProto.internal_static_XTableMessage_descriptor;
      }

      @java.lang.Override
      public XTableProto.XTableMessage getDefaultInstanceForType() {
        return XTableProto.XTableMessage.getDefaultInstance();
      }

      @java.lang.Override
      public XTableProto.XTableMessage build() {
        XTableProto.XTableMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public XTableProto.XTableMessage buildPartial() {
        XTableProto.XTableMessage result = new XTableProto.XTableMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(XTableProto.XTableMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.command_ = command_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.key_ = key_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.value_ = value_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof XTableProto.XTableMessage) {
          return mergeFrom((XTableProto.XTableMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(XTableProto.XTableMessage other) {
        if (other == XTableProto.XTableMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasKey()) {
          key_ = other.key_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                command_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                key_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                value_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private int command_ = 0;
      /**
       * <code>optional .XTableMessage.Command command = 2;</code>
       * @return Whether the command field is set.
       */
      @java.lang.Override public boolean hasCommand() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .XTableMessage.Command command = 2;</code>
       * @return The enum numeric value on the wire for command.
       */
      @java.lang.Override public int getCommandValue() {
        return command_;
      }
      /**
       * <code>optional .XTableMessage.Command command = 2;</code>
       * @param value The enum numeric value on the wire for command to set.
       * @return This builder for chaining.
       */
      public Builder setCommandValue(int value) {
        command_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .XTableMessage.Command command = 2;</code>
       * @return The command.
       */
      @java.lang.Override
      public XTableProto.XTableMessage.Command getCommand() {
        XTableProto.XTableMessage.Command result = XTableProto.XTableMessage.Command.forNumber(command_);
        return result == null ? XTableProto.XTableMessage.Command.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .XTableMessage.Command command = 2;</code>
       * @param value The command to set.
       * @return This builder for chaining.
       */
      public Builder setCommand(XTableProto.XTableMessage.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        command_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .XTableMessage.Command command = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000002);
        command_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 3;</code>
       * @return Whether the key field is set.
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string key = 3;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 3;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 3;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 3;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        key_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes value = 4;</code>
       * @return Whether the value field is set.
       */
      @java.lang.Override
      public boolean hasValue() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes value = 4;</code>
       * @return The value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>optional bytes value = 4;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes value = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .XTableMessage.Type type = 5;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override public boolean hasType() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional .XTableMessage.Type type = 5;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .XTableMessage.Type type = 5;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional .XTableMessage.Type type = 5;</code>
       * @return The type.
       */
      @java.lang.Override
      public XTableProto.XTableMessage.Type getType() {
        XTableProto.XTableMessage.Type result = XTableProto.XTableMessage.Type.forNumber(type_);
        return result == null ? XTableProto.XTableMessage.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .XTableMessage.Type type = 5;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(XTableProto.XTableMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .XTableMessage.Type type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:XTableMessage)
    }

    // @@protoc_insertion_point(class_scope:XTableMessage)
    private static final XTableProto.XTableMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new XTableProto.XTableMessage();
    }

    public static XTableProto.XTableMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<XTableMessage>
        PARSER = new com.google.protobuf.AbstractParser<XTableMessage>() {
      @java.lang.Override
      public XTableMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<XTableMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<XTableMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public XTableProto.XTableMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_XTableMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_XTableMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021XTableProto.proto\"\201\005\n\rXTableMessage\022\017\n" +
      "\002id\030\001 \001(\003H\000\210\001\001\022,\n\007command\030\002 \001(\0162\026.XTable" +
      "Message.CommandH\001\210\001\001\022\020\n\003key\030\003 \001(\tH\002\210\001\001\022\022" +
      "\n\005value\030\004 \001(\014H\003\210\001\001\022&\n\004type\030\005 \001(\0162\023.XTabl" +
      "eMessage.TypeH\004\210\001\001\"y\n\004Type\022\013\n\007UNKNOWN\020\000\022" +
      "\n\n\006STRING\020\001\022\n\n\006DOUBLE\020\002\022\t\n\005INT64\020\005\022\010\n\004BO" +
      "OL\020\006\022\t\n\005BYTES\020\007\022\010\n\004ENUM\020\010\022\013\n\007MESSAGE\020\t\022\t" +
      "\n\005ARRAY\020\n\022\n\n\006OBJECT\020\013\"\271\002\n\007Command\022\023\n\017UNK" +
      "NOWN_COMMAND\020\000\022\007\n\003PUT\020\001\022\007\n\003GET\020\002\022\024\n\020SUBS" +
      "CRIBE_UPDATE\020\003\022\016\n\nGET_TABLES\020\004\022\016\n\nRUN_SC" +
      "RIPT\020\005\022\016\n\nUPDATE_KEY\020\006\022\n\n\006DELETE\020\007\022\013\n\007PU" +
      "BLISH\020\010\022\024\n\020SUBSCRIBE_DELETE\020\t\022\026\n\022UNSUBSC" +
      "RIBE_DELETE\020\n\022\026\n\022UNSUBSCRIBE_UPDATE\020\013\022\010\n" +
      "\004PING\020\014\022\020\n\014GET_RAW_JSON\020\r\022\020\n\014DELETE_EVEN" +
      "T\020\016\022\020\n\014UPDATE_EVENT\020\017\022\017\n\013INFORMATION\020\020\022\021" +
      "\n\rREBOOT_SERVER\020\021B\005\n\003_idB\n\n\010_commandB\006\n\004" +
      "_keyB\010\n\006_valueB\007\n\005_typeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_XTableMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_XTableMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_XTableMessage_descriptor,
        new java.lang.String[] { "Id", "Command", "Key", "Value", "Type", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
