// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/XTableValues.proto
// Protobuf Java Version: 4.29.2

package org.kobe.xbot.Utilities.Entities;

public final class XTableValues {
  private XTableValues() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      XTableValues.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CoordinateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.kobe.xbot.Utilities.Entities.Coordinate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double x = 1;</code>
     * @return The x.
     */
    double getX();

    /**
     * <code>double y = 2;</code>
     * @return The y.
     */
    double getY();
  }
  /**
   * Protobuf type {@code org.kobe.xbot.Utilities.Entities.Coordinate}
   */
  public static final class Coordinate extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.kobe.xbot.Utilities.Entities.Coordinate)
      CoordinateOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        Coordinate.class.getName());
    }
    // Use Coordinate.newBuilder() to construct.
    private Coordinate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Coordinate() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kobe.xbot.Utilities.Entities.XTableValues.internal_static_org_kobe_xbot_Utilities_Entities_Coordinate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kobe.xbot.Utilities.Entities.XTableValues.internal_static_org_kobe_xbot_Utilities_Entities_Coordinate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.class, org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private double x_ = 0D;
    /**
     * <code>double x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private double y_ = 0D;
    /**
     * <code>double y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public double getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        output.writeDouble(1, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        output.writeDouble(2, y_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate)) {
        return super.equals(obj);
      }
      org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate other = (org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate) obj;

      if (java.lang.Double.doubleToLongBits(getX())
          != java.lang.Double.doubleToLongBits(
              other.getX())) return false;
      if (java.lang.Double.doubleToLongBits(getY())
          != java.lang.Double.doubleToLongBits(
              other.getY())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getY()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.kobe.xbot.Utilities.Entities.Coordinate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.kobe.xbot.Utilities.Entities.Coordinate)
        org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kobe.xbot.Utilities.Entities.XTableValues.internal_static_org_kobe_xbot_Utilities_Entities_Coordinate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kobe.xbot.Utilities.Entities.XTableValues.internal_static_org_kobe_xbot_Utilities_Entities_Coordinate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.class, org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.Builder.class);
      }

      // Construct using org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x_ = 0D;
        y_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kobe.xbot.Utilities.Entities.XTableValues.internal_static_org_kobe_xbot_Utilities_Entities_Coordinate_descriptor;
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate getDefaultInstanceForType() {
        return org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.getDefaultInstance();
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate build() {
        org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate buildPartial() {
        org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate result = new org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate) {
          return mergeFrom((org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate other) {
        if (other == org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.getDefaultInstance()) return this;
        if (other.getX() != 0D) {
          setX(other.getX());
        }
        if (other.getY() != 0D) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                x_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                y_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double x_ ;
      /**
       * <code>double x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public double getX() {
        return x_;
      }
      /**
       * <code>double x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(double value) {

        x_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>double y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public double getY() {
        return y_;
      }
      /**
       * <code>double y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(double value) {

        y_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.kobe.xbot.Utilities.Entities.Coordinate)
    }

    // @@protoc_insertion_point(class_scope:org.kobe.xbot.Utilities.Entities.Coordinate)
    private static final org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate();
    }

    public static org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Coordinate>
        PARSER = new com.google.protobuf.AbstractParser<Coordinate>() {
      @java.lang.Override
      public Coordinate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Coordinate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Coordinate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CoordinateListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.kobe.xbot.Utilities.Entities.CoordinateList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
     */
    java.util.List<org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate> 
        getCoordinatesList();
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
     */
    org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate getCoordinates(int index);
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
     */
    int getCoordinatesCount();
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
     */
    java.util.List<? extends org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateOrBuilder> 
        getCoordinatesOrBuilderList();
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
     */
    org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateOrBuilder getCoordinatesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.kobe.xbot.Utilities.Entities.CoordinateList}
   */
  public static final class CoordinateList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.kobe.xbot.Utilities.Entities.CoordinateList)
      CoordinateListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        CoordinateList.class.getName());
    }
    // Use CoordinateList.newBuilder() to construct.
    private CoordinateList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CoordinateList() {
      coordinates_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kobe.xbot.Utilities.Entities.XTableValues.internal_static_org_kobe_xbot_Utilities_Entities_CoordinateList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kobe.xbot.Utilities.Entities.XTableValues.internal_static_org_kobe_xbot_Utilities_Entities_CoordinateList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList.class, org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList.Builder.class);
    }

    public static final int COORDINATES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate> coordinates_;
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate> getCoordinatesList() {
      return coordinates_;
    }
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateOrBuilder> 
        getCoordinatesOrBuilderList() {
      return coordinates_;
    }
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
     */
    @java.lang.Override
    public int getCoordinatesCount() {
      return coordinates_.size();
    }
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
     */
    @java.lang.Override
    public org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate getCoordinates(int index) {
      return coordinates_.get(index);
    }
    /**
     * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
     */
    @java.lang.Override
    public org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateOrBuilder getCoordinatesOrBuilder(
        int index) {
      return coordinates_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < coordinates_.size(); i++) {
        output.writeMessage(1, coordinates_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < coordinates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, coordinates_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList)) {
        return super.equals(obj);
      }
      org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList other = (org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList) obj;

      if (!getCoordinatesList()
          .equals(other.getCoordinatesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCoordinatesCount() > 0) {
        hash = (37 * hash) + COORDINATES_FIELD_NUMBER;
        hash = (53 * hash) + getCoordinatesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.kobe.xbot.Utilities.Entities.CoordinateList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.kobe.xbot.Utilities.Entities.CoordinateList)
        org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kobe.xbot.Utilities.Entities.XTableValues.internal_static_org_kobe_xbot_Utilities_Entities_CoordinateList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kobe.xbot.Utilities.Entities.XTableValues.internal_static_org_kobe_xbot_Utilities_Entities_CoordinateList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList.class, org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList.Builder.class);
      }

      // Construct using org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (coordinatesBuilder_ == null) {
          coordinates_ = java.util.Collections.emptyList();
        } else {
          coordinates_ = null;
          coordinatesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kobe.xbot.Utilities.Entities.XTableValues.internal_static_org_kobe_xbot_Utilities_Entities_CoordinateList_descriptor;
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList getDefaultInstanceForType() {
        return org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList.getDefaultInstance();
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList build() {
        org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList buildPartial() {
        org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList result = new org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList result) {
        if (coordinatesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            coordinates_ = java.util.Collections.unmodifiableList(coordinates_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.coordinates_ = coordinates_;
        } else {
          result.coordinates_ = coordinatesBuilder_.build();
        }
      }

      private void buildPartial0(org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList) {
          return mergeFrom((org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList other) {
        if (other == org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList.getDefaultInstance()) return this;
        if (coordinatesBuilder_ == null) {
          if (!other.coordinates_.isEmpty()) {
            if (coordinates_.isEmpty()) {
              coordinates_ = other.coordinates_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCoordinatesIsMutable();
              coordinates_.addAll(other.coordinates_);
            }
            onChanged();
          }
        } else {
          if (!other.coordinates_.isEmpty()) {
            if (coordinatesBuilder_.isEmpty()) {
              coordinatesBuilder_.dispose();
              coordinatesBuilder_ = null;
              coordinates_ = other.coordinates_;
              bitField0_ = (bitField0_ & ~0x00000001);
              coordinatesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCoordinatesFieldBuilder() : null;
            } else {
              coordinatesBuilder_.addAllMessages(other.coordinates_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate m =
                    input.readMessage(
                        org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.parser(),
                        extensionRegistry);
                if (coordinatesBuilder_ == null) {
                  ensureCoordinatesIsMutable();
                  coordinates_.add(m);
                } else {
                  coordinatesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate> coordinates_ =
        java.util.Collections.emptyList();
      private void ensureCoordinatesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          coordinates_ = new java.util.ArrayList<org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate>(coordinates_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate, org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.Builder, org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateOrBuilder> coordinatesBuilder_;

      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public java.util.List<org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate> getCoordinatesList() {
        if (coordinatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(coordinates_);
        } else {
          return coordinatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public int getCoordinatesCount() {
        if (coordinatesBuilder_ == null) {
          return coordinates_.size();
        } else {
          return coordinatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate getCoordinates(int index) {
        if (coordinatesBuilder_ == null) {
          return coordinates_.get(index);
        } else {
          return coordinatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public Builder setCoordinates(
          int index, org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate value) {
        if (coordinatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoordinatesIsMutable();
          coordinates_.set(index, value);
          onChanged();
        } else {
          coordinatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public Builder setCoordinates(
          int index, org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.Builder builderForValue) {
        if (coordinatesBuilder_ == null) {
          ensureCoordinatesIsMutable();
          coordinates_.set(index, builderForValue.build());
          onChanged();
        } else {
          coordinatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public Builder addCoordinates(org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate value) {
        if (coordinatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoordinatesIsMutable();
          coordinates_.add(value);
          onChanged();
        } else {
          coordinatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public Builder addCoordinates(
          int index, org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate value) {
        if (coordinatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoordinatesIsMutable();
          coordinates_.add(index, value);
          onChanged();
        } else {
          coordinatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public Builder addCoordinates(
          org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.Builder builderForValue) {
        if (coordinatesBuilder_ == null) {
          ensureCoordinatesIsMutable();
          coordinates_.add(builderForValue.build());
          onChanged();
        } else {
          coordinatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public Builder addCoordinates(
          int index, org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.Builder builderForValue) {
        if (coordinatesBuilder_ == null) {
          ensureCoordinatesIsMutable();
          coordinates_.add(index, builderForValue.build());
          onChanged();
        } else {
          coordinatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public Builder addAllCoordinates(
          java.lang.Iterable<? extends org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate> values) {
        if (coordinatesBuilder_ == null) {
          ensureCoordinatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, coordinates_);
          onChanged();
        } else {
          coordinatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public Builder clearCoordinates() {
        if (coordinatesBuilder_ == null) {
          coordinates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          coordinatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public Builder removeCoordinates(int index) {
        if (coordinatesBuilder_ == null) {
          ensureCoordinatesIsMutable();
          coordinates_.remove(index);
          onChanged();
        } else {
          coordinatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.Builder getCoordinatesBuilder(
          int index) {
        return getCoordinatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateOrBuilder getCoordinatesOrBuilder(
          int index) {
        if (coordinatesBuilder_ == null) {
          return coordinates_.get(index);  } else {
          return coordinatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public java.util.List<? extends org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateOrBuilder> 
           getCoordinatesOrBuilderList() {
        if (coordinatesBuilder_ != null) {
          return coordinatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(coordinates_);
        }
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.Builder addCoordinatesBuilder() {
        return getCoordinatesFieldBuilder().addBuilder(
            org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.getDefaultInstance());
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.Builder addCoordinatesBuilder(
          int index) {
        return getCoordinatesFieldBuilder().addBuilder(
            index, org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.getDefaultInstance());
      }
      /**
       * <code>repeated .org.kobe.xbot.Utilities.Entities.Coordinate coordinates = 1;</code>
       */
      public java.util.List<org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.Builder> 
           getCoordinatesBuilderList() {
        return getCoordinatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate, org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.Builder, org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateOrBuilder> 
          getCoordinatesFieldBuilder() {
        if (coordinatesBuilder_ == null) {
          coordinatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate, org.kobe.xbot.Utilities.Entities.XTableValues.Coordinate.Builder, org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateOrBuilder>(
                  coordinates_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          coordinates_ = null;
        }
        return coordinatesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.kobe.xbot.Utilities.Entities.CoordinateList)
    }

    // @@protoc_insertion_point(class_scope:org.kobe.xbot.Utilities.Entities.CoordinateList)
    private static final org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList();
    }

    public static org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CoordinateList>
        PARSER = new com.google.protobuf.AbstractParser<CoordinateList>() {
      @java.lang.Override
      public CoordinateList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CoordinateList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CoordinateList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.kobe.xbot.Utilities.Entities.XTableValues.CoordinateList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_kobe_xbot_Utilities_Entities_Coordinate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_kobe_xbot_Utilities_Entities_Coordinate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_kobe_xbot_Utilities_Entities_CoordinateList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_kobe_xbot_Utilities_Entities_CoordinateList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031protos/XTableValues.proto\022 org.kobe.xb" +
      "ot.Utilities.Entities\"\"\n\nCoordinate\022\t\n\001x" +
      "\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\"S\n\016CoordinateList\022A\n\013c" +
      "oordinates\030\001 \003(\0132,.org.kobe.xbot.Utiliti" +
      "es.Entities.Coordinateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_kobe_xbot_Utilities_Entities_Coordinate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_kobe_xbot_Utilities_Entities_Coordinate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_kobe_xbot_Utilities_Entities_Coordinate_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_org_kobe_xbot_Utilities_Entities_CoordinateList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_kobe_xbot_Utilities_Entities_CoordinateList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_kobe_xbot_Utilities_Entities_CoordinateList_descriptor,
        new java.lang.String[] { "Coordinates", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
