name: Build and Upload Python Wheel

on:
  push:
    branches:
      - master  # Change if needed
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine

      # Clean up old build files
      - name: Clean up old build files
        run: |
          rm -rf src/main/python/build src/main/python/dist src/main/python/*.egg-info

      # Build the package (pure Python wheel)
      - name: Build Python wheel
        working-directory: src/main/python
        run: |
          python -m pip wheel . --wheel-dir dist

      # Upload wheel artifacts for inspection
      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels
          path: src/main/python/dist/*.whl

      # Upload the package to PyPI
      - name: Upload package to PyPI
        working-directory: src/main/python
        run: |
          twine upload dist/* -u __token__ -p "${{ secrets.PYPI_API_TOKEN }}"
