name: Delete Old Package Versions

on:
  workflow_dispatch: # Run this workflow manually

jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: org.kobe.xbot.xtables # Replace with your package name
          package-type: maven # Supported values: 'container', 'npm', 'maven', 'rubygems', 'nuget'
          min-versions-to-keep: 5 # Keep at least 5 latest versions
          delete-only-pre-release-versions: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
