name: Upload and Cleanup Java Package

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual execution

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  delete-packages:
    runs-on: ubuntu-latest
    needs: publish # Ensures cleanup only runs after a successful package upload
    if: success() # Only runs if the publish job is successful

    steps:
      - name: Delete Old Package Versions
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: org.kobe.xbot.xtables # Replace with your package name
          package-type: maven
          min-versions-to-keep: 5
          delete-only-pre-release-versions: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
