name: Upload Python Package

# Trigger on every push to the repository (you can specify branches if needed)
on:
  push:
    branches:
      - master  # Change 'master' to your default branch name if different
    # Optionally add tags or specific files you want to trigger on

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Install required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine

      # Step 1: Clean up old build files in the correct directory
      - name: Clean up old build files
        run: |
          rm -rf src/main/python/build src/main/python/dist src/main/python*.egg-info

      # Step 2: Build the package (source distribution and wheel) from the correct directory
      - name: Build release distributions
        run: |
          cd src/main/python
          python setup.py sdist bdist_wheel

      # Step 3: Upload distributions to PyPI using twine
      - name: Upload package to PyPI
        run: |
          twine upload src/main/python/dist/* -u __token__ -p "${{ secrets.PYPI_API_TOKEN }}"
