name: Create ZIP on Push

on:
  push:
    branches:
      - master

jobs:
  zip_directories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install zip utility
      run: sudo apt-get install -y zip

    - name: Create ZIP of JClient and Utilities
      run: |
        mkdir -p output
        zip -r output/jclient.zip src/main/java/org/kobe/xbot/JClient src/main/java/org/kobe/xbot/Utilities

    - name: Commit and Push ZIP to Repository
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b zip-files || git checkout zip-files
        mkdir -p zips
        cp output/jclient.zip zips/
        git add zips/jclient.zip
        git commit -m "Add JClient ZIP on push"
        git push origin zip-files
